import click
import multiprocessing
import sys
import logging
from os import getpid
import tkinter as tk
from tkinter import ttk
import traceback
from logging import Handler, StreamHandler, getLogger
from concurrent.futures import ProcessPoolExecutor, wait
from pysagax.field.streamer import Streamer
from typing import Any, Optional
from time import time, sleep
from queue import Queue
import queue
from numpy import deg2rad, rad2deg
from scipy.spatial.transform import Rotation
import threading

from pysagax.communication.req_rep_tcp import REP
from pysagax.ui.custom_widgets import EntryWithLabel, ToggleButton

from signal import SIGINT, SIGTERM, signal

from pysagax.common.loop import Loop
import pysagax.message.command_pb2 as proto_cmd
import pysagax.message.data_pb2 as proto_data
import pysagax.message.heading_pb2 as proto_heading

from pysagax.util.mat import si_to_float, quat, ypr


import google.protobuf.message
import numpy as np


from pysagax.analyzing_tools.mock.mock_packets import *



class SimulatedEntryWithLabel:
    def __init__(
        self,
        master: tk.Misc,
        labeltext: str,
        column: int,
        row: int,
        default_value: str = (0, 0, 0),
        width: int = 11,
        padx: int = 5,
        pady: int = 5,
    ) -> None:
        """
        tkinter widget of a label, entry box and tkinter variable combined to be used in frames with columnconfigure
        """
        self.mu = tk.StringVar(value=default_value[0])
        self.sigma = tk.StringVar(value=default_value[1])
        self.delta = tk.StringVar(value=default_value[2])

        self.label = ttk.Label(master, text=labeltext)
        self.mu_label = ttk.Label(master, text="μ:")
        self.sigma_label = ttk.Label(master, text="σ:")
        self.delta_label = ttk.Label(master, text="δ:")
        self.label.grid(column=column, row=row, sticky=tk.W, padx=padx, pady=pady)

        self.mu_label.grid(
            column=column + 1, row=row, sticky=tk.W, padx=padx, pady=pady
        )
        self.sigma_label.grid(
            column=column + 3, row=row, sticky=tk.W, padx=padx, pady=pady
        )
        self.delta_label.grid(
            column=column + 5, row=row, sticky=tk.W, padx=padx, pady=pady
        )

        self.mu_entry = ttk.Entry(master, textvariable=self.mu, width=width)
        self.mu_entry.grid(
            column=column + 2,
            row=row,
            sticky=tk.E + tk.W,
            padx=padx,
            pady=pady,
        )
        self.sigma_entry = ttk.Entry(master, textvariable=self.sigma, width=width)
        self.sigma_entry.grid(
            column=column + 4,
            row=row,
            sticky=tk.E + tk.W,
            padx=padx,
            pady=pady,
        )
        self.delta_entry = ttk.Entry(master, textvariable=self.delta, width=width)
        self.delta_entry.grid(
            column=column + 6,
            row=row,
            sticky=tk.E + tk.W,
            padx=padx,
            pady=pady,
        )

    def get(self, to_radian=False) -> Any:
        if to_radian:
            return tuple(deg2rad(si_to_float(str(p.get()))) for p in (self.mu, self.sigma, self.delta))
        else:
            return tuple(si_to_float(str(p.get())) for p in (self.mu, self.sigma, self.delta))

    def set(self, p: Parameter, to_degree=False):
        if to_degree:
            self.mu.set(round(rad2deg(p.mu), 6))
            self.sigma.set(round(rad2deg(p.sigma), 6))
            self.delta.set(round(rad2deg(p.delta), 6))
        else:
            self.mu.set(round(p.mu, 6))
            self.sigma.set(round(p.sigma, 6))
            self.delta.set(round(p.delta, 6))

    # def set(self, value: Any) -> Any:
    #     return (
    #         self.mu.set(value=[0]),
    #         self.sigma.set(value=[1]),
    #         self.delta.set(value=value[2]),
    #     )

    def destroy(self) -> None:
        self.label.destroy()
        self.mu_label.destroy()
        self.sigma_label.destroy()
        self.delta_label.destroy()
        self.mu_entry.destroy()
        self.sigma_entry.destroy()
        self.delta_entry.destroy()
        # return super().destroy()

    def configure(self, **kwargs):
        for entry in [self.mu_entry, self.sigma_entry, self.delta_entry]:
            entry.configure(**kwargs)


class App:
    def __init__(self, root, queue_in, queue_out, command_port):
        self.root = root
        self.queue_in = queue_in
        self.queue_out = queue_out
        self._command_port = command_port

        # The latest packet generated by PacketFactory. 
        self.latest_generated__measurement = SimulatedMeasurement()
        # The last packet submitted from the GUI
        self.latest_submitted_measurement = SimulatedMeasurement()
        self.edit_mode = True

        self.stream_id = EntryWithLabel(root, "Stream id", 0, 0, variable_type=tk.IntVar)
        self.config_id = EntryWithLabel(root, "Config id", 0, 1, variable_type=tk.IntVar)
        # self.overflow = EntryWithLabel(root, "Overflow", 0, , variable_type=tk.BoolVar)

        self.yaw = SimulatedEntryWithLabel(root, "yaw", 0, 3)
        self.pitch = SimulatedEntryWithLabel(root, "pitch", 0, 4)
        self.roll = SimulatedEntryWithLabel(root, "roll", 0, 5)
        self.gps_lat = SimulatedEntryWithLabel(root, "gps_lat", 0, 6)
        self.gps_lon = SimulatedEntryWithLabel(root, "gps_lon", 0, 7)
        self.altitude = SimulatedEntryWithLabel(root, "altitude", 0, 8)
        self.offset = EntryWithLabel(root, "offset", 0, 9, variable_type=tk.DoubleVar)



        self.event_id = EntryWithLabel(root, "Event id", 0, 10, variable_type=tk.IntVar)
        self.roi_id = EntryWithLabel(root, "ROI id", 0, 11, variable_type=tk.IntVar)
        self.frequency = SimulatedEntryWithLabel(root, "frequency", 0, 12)
        self.azimuth = SimulatedEntryWithLabel(root, "azimuth", 0, 13)
        self.mean_azimuth = SimulatedEntryWithLabel(root, "mean_azimuth", 0, 14)
        self.elevation = SimulatedEntryWithLabel(root, "elevation", 0, 15)
        self.mean_elevation = SimulatedEntryWithLabel(root, "mean_elevation", 0, 16)
        self.deviation = SimulatedEntryWithLabel(root, "deviation", 0, 17)
        



        self.stream_id = EntryWithLabel(root, "Stream id", 0, 0, variable_type=tk.IntVar)

        self.stream_id = EntryWithLabel(root, "Stream id", 0, 0, variable_type=tk.IntVar)


        self.button = tk.Button(root, text="Submit", command=self.submit)
        self.button.grid(row=40)


        tk.Label(root, text="Show current packet:").grid(row=45, column=0)
        self.toggle_mode = ToggleButton(root, self.enter_current_mode, self.enter_edit_mode, False)
        self.toggle_mode.grid(row=45, column=1, columnspan=2, pady=10, sticky="W")
        # tk.Label(root, text="Edit mode").grid(row=45, column=2)

        # Label to display status
        self.status = tk.Label(root, text="Running...")
        self.status.grid(row=51)

        self.entries = [self.stream_id, self.config_id, self.yaw, self.pitch, self.roll, self.gps_lat, self.gps_lon, self.altitude, self.offset, self.event_id, self.roi_id, self.frequency, self.azimuth, self.mean_azimuth, self.elevation, self.mean_elevation, self.deviation]

        self.refresh_entries(SimulatedMeasurement(detections=[SimulatedDetection()]))

        self.packet_handler_thread = threading.Thread(
            target=self.monitor_generated_packets, daemon=True
        )
        self.packet_handler_thread.start()
        # self.updtate_gui_thread = threading.Thread(
        #     target=self.gui_updater, daemon=True
        # )
        # self.updtate_gui_thread.start()
        self.gui_updater()

    def monitor_generated_packets(self):
        while True:
            try:
                # for 
                packet = self.queue_in.get(timeout=0)
                self.latest_generated__measurement = packet
            except queue.Empty:
                sleep(0.1)
            # print("run")
        pass

    def gui_updater(self):
        self.root.after(100, self.gui_updater)
        if not self.edit_mode:
            self.refresh_entries(self.latest_generated__measurement)
            # sleep(.1)

    def refresh_entries(self, sm:SimulatedMeasurement):
        self.stream_id.set(sm.stream_id)
        self.config_id.set(sm.config_id)
        self.yaw.set(sm.heading_data.yaw, True)
        self.pitch.set(sm.heading_data.pitch, True)
        self.roll.set(sm.heading_data.roll, True)
        self.gps_lat.set(sm.heading_data.gps_lat)
        self.gps_lon.set(sm.heading_data.gps_lon)
        self.altitude.set(sm.heading_data.altitude)
        self.offset.set(sm.heading_data.offset) #TODO: to degree and radian

        if not len(sm.detections):
            # fill with default
            sm.detections = [SimulatedDetection()]
        self.event_id.set(sm.detections[0].event_id)
        self.roi_id.set(sm.detections[0].roi_id)
        self.frequency.set(sm.detections[0].frequency)
        self.azimuth.set(sm.detections[0].azimuth, True)
        self.mean_azimuth.set(sm.detections[0].mean_azimuth, True)
        self.elevation.set(sm.detections[0].elevation, True)
        self.mean_elevation.set(sm.detections[0].mean_elevation, True)
        self.deviation.set(sm.detections[0].deviation, True)

    def submit(self):
        # Push the entry content to the queue
        # text = self.entry.get()         
        sm = SimulatedMeasurement(
            # stream_id=self.stream_id.get(),
            config_id = self.config_id.get(),
            overflow=False,
            peaks=(10000, 10000, 10000, 10000),
            heading_data = SimulatedHeading(
                packet_id = 0, 
                yaw=self.yaw.get(True),
                pitch=self.pitch.get(True),
                roll=self.roll.get(True),
                gps_lat=self.gps_lat.get(),
                gps_lon=self.gps_lon.get(), 
                altitude=self.altitude.get(),
                offset=self.offset.get(),)
                , 
            detections=[
                SimulatedDetection(
                    event_id = self.event_id.get(), 
                    roi_id = self.roi_id.get(),
                    frequency=self.frequency.get(),
                    azimuth=self.azimuth.get(True),
                    mean_azimuth=self.mean_azimuth.get(True),
                    elevation=self.elevation.get(True),
                    mean_elevation=self.mean_elevation.get(True),
                    deviation=self.deviation.get(True),
                ),
            ]
        )

        # sm.detections[0].azimuth.sigma = 20 / 180 * np.pi
        # sm.detections[0].frequency.mu = 300
        self.latest_submitted_measurement = sm
        self.queue_out.put(sm)

    def update_status(self, done):
        if done:
            self.status.config(text="Processes Complete")
        else:
            self.status.config(text=f"Running on port {self._command_port}")

    def enter_current_mode(self):
        self.edit_mode = False
        for entry in self.entries:
            entry.configure(state="disabled")
        self.button.configure(state="disabled")
        # self.refresh_entries(self.latest_generated__measurement)

    def enter_edit_mode(self):
        self.edit_mode = True
        for entry in self.entries:
            entry.configure(state="enabled")
        self.button.configure(state="normal")
        # sleep(1)
        self.refresh_entries(self.latest_submitted_measurement)
        