"""
Run this to mock a single pysagaxUAV output stream.
    -> Streams  generated measurement packets with mocked heading and detection data.
    -> Use the GUI to set it up (currently can't run without gui)
To mock MULTIPLE pysagaxUAV instances (all detecting the same target), run mock_target.py.
"""


import click
import multiprocessing
import sys
import logging
from os import getpid
import tkinter as tk
from tkinter import ttk
import traceback
from logging import Handler, StreamHandler, getLogger
from concurrent.futures import ProcessPoolExecutor, wait
from pysagax.field.streamer import Streamer
from typing import Any, Optional
from time import time, sleep
from queue import Queue
import queue
from numpy import deg2rad, rad2deg
from scipy.spatial.transform import Rotation

from pysagax.communication.req_rep_tcp import REP
from pysagax.ui.custom_widgets import EntryWithLabel

from signal import SIGINT, SIGTERM, signal

from pysagax.common.loop import Loop
import pysagax.message.command_pb2 as proto_cmd
import pysagax.message.data_pb2 as proto_data
import pysagax.message.heading_pb2 as proto_heading

from pysagax.util.mat import si_to_float, quat, ypr


import google.protobuf.message
import numpy as np

from pysagax.analyzing_tools.mock.mock_packets import *
from pysagax.analyzing_tools.mock.mock_uav_gui import *


class PacketFactory(Loop):
    """Pushes a packet generated by SimulatedMeasurement to the Streamer with the defined frequency"""

    def __init__(self, level, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._queue_out: Optional[Queue] = None
        self._queue_in: Optional[Queue] = None
        self._latest_packet = proto_data.Measurement()
        self.push_interval = 0.1  # 1 / number of packets to be pushed per second
        self._latest_push = time()
        # self.detections = []
        self.measurement_packet = SimulatedMeasurement()

    def __call__(
        self, queue_out: Queue[Any], queue_in: Optional[Queue] = None, to_gui_queue = None, *args, **kwargs
    ) -> None:
        self._queue_out = queue_out #to streamer
        self._queue_in = queue_in
        self._to_gui_queue = to_gui_queue
        return super()._call(*args, **kwargs)

    def _loop(self) -> None:
        assert self._queue_out is not None

        if self._queue_in is not None:
            print("q out is not none")
            try:
                print("aaaaa")
                new_sm = self._queue_in.get_nowait()
                self.measurement_packet.update(new_sm)
            except queue.Empty:
                pass
        elapsed_time = time() - self._latest_push
        if elapsed_time < self.push_interval:
            sleep(self.push_interval - elapsed_time)
        # packet = proto_data.Measurement(        )
        timestamp = time()
        # packet.time.seconds = int(timestamp)
        # packet.time.nanos = int(timestamp % 1 * 1e9)

        # packet =
        packet = self.measurement_packet.get_packet()
        print("PACKET: ", packet)
        self._latest_push = time()
        self._queue_out.put(packet)
        if self._to_gui_queue is not None:
            self._to_gui_queue.put(self.measurement_packet)


class MockCommunicator(Loop):
    def __init__(self, port: int = 5556, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)

        # Set up command channel
        self._server: Optional[REP] = None
        self._queue_out: Optional[Queue] = None
        self._port = port

    def __call__(self, queue_out: Queue[Any], *args, **kwargs) -> None:
        self._queue_out = queue_out
        self._server = REP(port_server=self._port)
        self._logger.info(f"Listening ZMQ REP on {self._port}/tcp")
        # self._logger.debug(vars(self._server))
        return super()._call(*args, **kwargs)

    def _pre_loop(self) -> None:
        # Connect and bind communication ports
        assert self._server is not None
        self._server.connect()

    def _loop(self) -> None:
        assert self._server is not None
        assert self._queue_out is not None

        raw_command = self._server.recv()
        command = proto_cmd.Command()
        command.ParseFromString(raw_command)

        if command.instruction in [proto_cmd.STREAM_START, proto_cmd.STREAM_STOP]:
            self._queue_out.put(command)

        response = proto_cmd.Response(success=True)
        raw_response = response.SerializeToString()
        self._server.resp(raw_response)


class Commander:
    def __init__(self, level, command_port, show_gui=False):
        self._logger = getLogger("Commander")
        self._show_gui = show_gui
        self._command_port = command_port

        self._manager = multiprocessing.Manager()
        self._pool = ProcessPoolExecutor(max_workers=14)

        self._stream_packets_q = self._manager.Queue(maxsize=8)
        self._stream_conf_q = self._manager.Queue()
        if self._show_gui:
            self._gui_out_q = self._manager.Queue()
            self._gui_in_q = self._manager.Queue()
        else:
            self._gui_out_q = None
            self._gui_in_q = None

        print("HENLO WOERLD")
        self._packet_factory = PacketFactory(level=level)
        self._communicator = MockCommunicator(level=level, port=command_port)
        self._streamer = Streamer(level=level)

    def start(self):
        print("asd")
        packet_factory_future = self._pool.submit(
            self._packet_factory,
            self._stream_packets_q,
            self._gui_out_q,
            self._gui_in_q
        )
        print("asd2")
        communicator_future = self._pool.submit(self._communicator, self._stream_conf_q)
        print("asd3")
        streamer_future = self._pool.submit(
            self._streamer, self._stream_packets_q, self._stream_conf_q
        )

        signal(SIGINT, self._signal_handler)
        signal(SIGTERM, self._signal_handler)
        if self._show_gui:
            # TODO init app
            root = tk.Tk()
            app = App(root, self._gui_in_q, self._gui_out_q, command_port = self._command_port)
            print("ASDFASDFASDF")
            root.after(
                100,
                self._monitor_with_gui,
                app,
                packet_factory_future,
                communicator_future,
                streamer_future,
            )
            root.mainloop()
            self._monitor_with_gui(
                app, packet_factory_future, communicator_future, streamer_future
            )
        else:
            self._monitor_wo_gui(
                packet_factory_future, communicator_future, streamer_future
            )

    def _monitor_with_gui(
        self, app, packet_factory_future, communicator_future, streamer_future
    ):
        done, running = wait(
            (packet_factory_future, communicator_future, streamer_future), timeout=1
        )
        app.update_status(len(done) >= 3)
        if len(done) >= 3:
            # Send quit signal to worker processes
            app.queue.put("QUIT")
            app.root.quit()
        else:
            # Schedule next check
            app.root.after(
                100,
                self._monitor_with_gui,
                app,
                packet_factory_future,
                communicator_future,
                streamer_future,
            )

    def _monitor_wo_gui(
        self, packet_factory_future, communicator_future, streamer_future
    ):
        while True:
            done, running = wait(
                (
                    packet_factory_future,
                    communicator_future,
                    streamer_future,
                ),
                timeout=1,
            )
            if self._pool._max_workers < len(running):
                self._logger.critical(
                    f"The number of workers ({len(running)}) exceeds the maximum "
                    f"set for ProcessPoolExecutor ({self._pool._max_workers})"
                )
                self._quit()
            for future in done:
                if future.exception(0) is not None:
                    # Trace is lost this way, TODO: fix it
                    self._logger.critical("Got exception")
                    traceback.print_exception(future.exception(0))
                    self._quit()

    def _signal_handler(self, signal, frame) -> None:
        """Handle incoming signals"""
        self._logger.info(f"Main received signal {signal} (Pid {getpid()}), exiting...")
        self._quit()

    def _quit(self) -> None:
        self._logger.critical("Terminating all processes")
        self._pool.shutdown()
        self._manager.shutdown()
        self._logger.critical("All processes terminated")
        sys.exit(0)


@click.command()
@click.option("--level", "-l", default="INFO", show_default=True, help="Logging level")
@click.option(
    "-p",
    "--path",
    type=str,
    required=False,
    help="Location for the .csv file",
)
@click.option(
    "--show-gui",
    type=bool,
    required=False,
    is_flag=True,
    show_default=False,
    default=False,
    help="Show tkinter window for easier usage",
)
@click.option(
    "--port",
    type=int,
    required=True,

    default=5556,
    help="Command port to connect to with the client or pysagaxGND",
)
def main(level: str, path: str, show_gui: bool = False, port: int = 5556):
    """
    Utility for mocking PysagaxUAV's output. Reads detectrec file and streams it to a target (or )

    OR: add detections, headings, deviations and stream it
    TODO


                              ┌───────────────┐
                              │    Factory    ┼─────────────┐
                              │               │             │
                              └───────────────┘             │
                                                    stream_packets_q
                                                            │
                                                            │
        ┌────────────────┐       stream_conf_q        ┌─────▼────┐
        │MockCommunicator├───────────────────────────►│ Streamer │
        └────┬──────▲────┘                            └───────┬──┘
             │      │                                      UDP│
             │  TCP │                                         │
             ▼      │                                         ▼

    """

    # Validate logging level format
    if level is None:
        level = "INFO"
    if isinstance(level, str):
        level = level.upper()

    # Configure logging format
    from pysagax.pysagax_uav import setup_logging

    setup_logging(level=level)
    print("port", port)

    commander = Commander(level, port, show_gui)
    commander.start()

    # if show_gui:

    #     multiprocessing.Process(target=run_commander, args=(level, port)).start()
    #     print("STARTED")
    #     sleep(20)
    # else:
    #     run_commander(level, port)


def run_commander(level, port):
    commander = Commander(level, port)
    commander.start()


if __name__ == "__main__":
    main()