"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import pysagax.message.data_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _Instruction:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _InstructionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Instruction.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    PING: _Instruction.ValueType  # 0
    """Send a string, receive it back
      parameter: ping_data [string]
      response:  ping_data [string]
    """
    CONFIG: _Instruction.ValueType  # 1
    """Set and query config information
      parameter: config [Config]
      response:  config [Config]
    """
    TELEMETRY: _Instruction.ValueType  # 2
    """Query telemetry information
      response:  telemetry [Telemetry]
    """
    INFO: _Instruction.ValueType  # 3
    """Query system information
      response:  info [Info]
    """
    PY_RESET: _Instruction.ValueType  # 8
    CS_START: _Instruction.ValueType  # 9
    """Start CoreService
      response:  success [bool]
    """
    CS_STOP: _Instruction.ValueType  # 10
    """Stop CoreService
      response:  success [bool]
    """
    CS_RESTART: _Instruction.ValueType  # 11
    """Restart CoreService
      response:  success [bool]
    """
    CS_PING: _Instruction.ValueType  # 12
    """Ping CoreService
      parameter: ping_data [string]
      response:  ping_data [string]
    """
    SOURCE_START: _Instruction.ValueType  # 13
    """Start playback from source
      response:  success [bool]
    """
    SOURCE_STOP: _Instruction.ValueType  # 14
    """Stop playback from source
      response:  success [bool]
    """
    POSITION: _Instruction.ValueType  # 15
    """Set playback position
      parameter: position [uint64]
      response:  position [uint64]
    """
    REC_START: _Instruction.ValueType  # 17
    """Start recording
      response:  success [bool]
    """
    REC_STOP: _Instruction.ValueType  # 18
    """Stop recording
      response:  success [bool]
    """
    HEADING_START: _Instruction.ValueType  # 21
    """Start Heading service
      response:  success [bool]
    """
    HEADING_STOP: _Instruction.ValueType  # 22
    """Stop Heading service
      response: success [bool]
    """
    HEADING_RESTART: _Instruction.ValueType  # 23
    """Restart Heading service
      response: success [bool]
    """
    STREAM_START: _Instruction.ValueType  # 25
    """Start streaming to target
      parameter: target [StreamTarget]
      response:  success [bool]
    """
    STREAM_STOP: _Instruction.ValueType  # 26
    """Stop streaming to target, or to all targets if not specified
      parameter: target [StreamTarget] - level parameter will be ignored
      response:  success [bool]
    """

class Instruction(_Instruction, metaclass=_InstructionEnumTypeWrapper):
    """Types of instructions that can be sent"""

PING: Instruction.ValueType  # 0
"""Send a string, receive it back
  parameter: ping_data [string]
  response:  ping_data [string]
"""
CONFIG: Instruction.ValueType  # 1
"""Set and query config information
  parameter: config [Config]
  response:  config [Config]
"""
TELEMETRY: Instruction.ValueType  # 2
"""Query telemetry information
  response:  telemetry [Telemetry]
"""
INFO: Instruction.ValueType  # 3
"""Query system information
  response:  info [Info]
"""
PY_RESET: Instruction.ValueType  # 8
CS_START: Instruction.ValueType  # 9
"""Start CoreService
  response:  success [bool]
"""
CS_STOP: Instruction.ValueType  # 10
"""Stop CoreService
  response:  success [bool]
"""
CS_RESTART: Instruction.ValueType  # 11
"""Restart CoreService
  response:  success [bool]
"""
CS_PING: Instruction.ValueType  # 12
"""Ping CoreService
  parameter: ping_data [string]
  response:  ping_data [string]
"""
SOURCE_START: Instruction.ValueType  # 13
"""Start playback from source
  response:  success [bool]
"""
SOURCE_STOP: Instruction.ValueType  # 14
"""Stop playback from source
  response:  success [bool]
"""
POSITION: Instruction.ValueType  # 15
"""Set playback position
  parameter: position [uint64]
  response:  position [uint64]
"""
REC_START: Instruction.ValueType  # 17
"""Start recording
  response:  success [bool]
"""
REC_STOP: Instruction.ValueType  # 18
"""Stop recording
  response:  success [bool]
"""
HEADING_START: Instruction.ValueType  # 21
"""Start Heading service
  response:  success [bool]
"""
HEADING_STOP: Instruction.ValueType  # 22
"""Stop Heading service
  response: success [bool]
"""
HEADING_RESTART: Instruction.ValueType  # 23
"""Restart Heading service
  response: success [bool]
"""
STREAM_START: Instruction.ValueType  # 25
"""Start streaming to target
  parameter: target [StreamTarget]
  response:  success [bool]
"""
STREAM_STOP: Instruction.ValueType  # 26
"""Stop streaming to target, or to all targets if not specified
  parameter: target [StreamTarget] - level parameter will be ignored
  response:  success [bool]
"""
global___Instruction = Instruction

@typing_extensions.final
class ROIMask(google.protobuf.message.Message):
    """A single Region of Interest"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ROI_ID_FIELD_NUMBER: builtins.int
    CENTER_FREQUENCY_FIELD_NUMBER: builtins.int
    SPAN_FIELD_NUMBER: builtins.int
    TRESHOLD_FIELD_NUMBER: builtins.int
    roi_id: builtins.int
    """ID for associating with Detections"""
    center_frequency: builtins.float
    """ROI parameters"""
    span: builtins.float
    treshold: builtins.float
    def __init__(
        self,
        *,
        roi_id: builtins.int = ...,
        center_frequency: builtins.float = ...,
        span: builtins.float = ...,
        treshold: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["center_frequency", b"center_frequency", "roi_id", b"roi_id", "span", b"span", "treshold", b"treshold"]) -> None: ...

global___ROIMask = ROIMask

@typing_extensions.final
class Heading(google.protobuf.message.Message):
    """A single Heading source"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class ParametersEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    TYPE_FIELD_NUMBER: builtins.int
    PARAMETERS_FIELD_NUMBER: builtins.int
    type: builtins.str
    """ID of"""
    @property
    def parameters(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """Commands and their descriptions/values"""
    def __init__(
        self,
        *,
        type: builtins.str = ...,
        parameters: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["parameters", b"parameters", "type", b"type"]) -> None: ...

global___Heading = Heading

@typing_extensions.final
class Config(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Type:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _TypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Config._Type.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        LIVE: Config._Type.ValueType  # 0
        RECORDED: Config._Type.ValueType  # 1

    class Type(_Type, metaclass=_TypeEnumTypeWrapper):
        """Type of source"""

    LIVE: Config.Type.ValueType  # 0
    RECORDED: Config.Type.ValueType  # 1

    CONFIG_ID_FIELD_NUMBER: builtins.int
    CENTER_FREQUENCY_FIELD_NUMBER: builtins.int
    IQ_RATE_FIELD_NUMBER: builtins.int
    PLAYBACK_SPEED_FIELD_NUMBER: builtins.int
    BIN_COUNT_FIELD_NUMBER: builtins.int
    BURST_STRIDE_FIELD_NUMBER: builtins.int
    CHANNEL_GAIN_FIELD_NUMBER: builtins.int
    SOURCE_PATH_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    ROI_FIELD_NUMBER: builtins.int
    HEADING_FIELD_NUMBER: builtins.int
    MEAN_WINDOW_FIELD_NUMBER: builtins.int
    config_id: builtins.int
    """Increments with every change. Used to validate streamed data against config"""
    center_frequency: builtins.float
    """CoreService parameters"""
    iq_rate: builtins.int
    playback_speed: builtins.float
    bin_count: builtins.int
    burst_stride: builtins.int
    @property
    def channel_gain(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    source_path: builtins.str
    """Source parameters"""
    type: global___Config.Type.ValueType
    @property
    def roi(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ROIMask]:
        """ROI mask, made up of individual regions"""
    @property
    def heading(self) -> global___Heading:
        """Heading source selection"""
    mean_window: builtins.float
    """PostProcessing parameters"""
    def __init__(
        self,
        *,
        config_id: builtins.int = ...,
        center_frequency: builtins.float = ...,
        iq_rate: builtins.int = ...,
        playback_speed: builtins.float = ...,
        bin_count: builtins.int = ...,
        burst_stride: builtins.int = ...,
        channel_gain: collections.abc.Iterable[builtins.int] | None = ...,
        source_path: builtins.str = ...,
        type: global___Config.Type.ValueType = ...,
        roi: collections.abc.Iterable[global___ROIMask] | None = ...,
        heading: global___Heading | None = ...,
        mean_window: builtins.float = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["heading", b"heading"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["bin_count", b"bin_count", "burst_stride", b"burst_stride", "center_frequency", b"center_frequency", "channel_gain", b"channel_gain", "config_id", b"config_id", "heading", b"heading", "iq_rate", b"iq_rate", "mean_window", b"mean_window", "playback_speed", b"playback_speed", "roi", b"roi", "source_path", b"source_path", "type", b"type"]) -> None: ...

global___Config = Config

@typing_extensions.final
class SystemInfo(google.protobuf.message.Message):
    """General system information"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class Hardware(google.protobuf.message.Message):
        """Information about general hardware components"""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        DISK_FIELD_NUMBER: builtins.int
        disk: builtins.int
        def __init__(
            self,
            *,
            disk: builtins.int = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["disk", b"disk"]) -> None: ...

    @typing_extensions.final
    class Software(google.protobuf.message.Message):
        """Information about software stack"""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        CS_VERSION_FIELD_NUMBER: builtins.int
        PYSAGAX_VERSION_FIELD_NUMBER: builtins.int
        cs_version: builtins.str
        pysagax_version: builtins.str
        def __init__(
            self,
            *,
            cs_version: builtins.str = ...,
            pysagax_version: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["cs_version", b"cs_version", "pysagax_version", b"pysagax_version"]) -> None: ...

    @typing_extensions.final
    class SDR(google.protobuf.message.Message):
        """Information about available SDR sources"""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        MODEL_FIELD_NUMBER: builtins.int
        model: builtins.str
        """A single SDR source"""
        def __init__(
            self,
            *,
            model: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["model", b"model"]) -> None: ...

    HARDWARE_FIELD_NUMBER: builtins.int
    SOFTWARE_FIELD_NUMBER: builtins.int
    HEADINGS_FIELD_NUMBER: builtins.int
    RADIOS_FIELD_NUMBER: builtins.int
    @property
    def hardware(self) -> global___SystemInfo.Hardware: ...
    @property
    def software(self) -> global___SystemInfo.Software: ...
    @property
    def headings(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Heading]:
        """Information about available Heading sources"""
    @property
    def radios(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SystemInfo.SDR]: ...
    def __init__(
        self,
        *,
        hardware: global___SystemInfo.Hardware | None = ...,
        software: global___SystemInfo.Software | None = ...,
        headings: collections.abc.Iterable[global___Heading] | None = ...,
        radios: collections.abc.Iterable[global___SystemInfo.SDR] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["hardware", b"hardware", "software", b"software"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["hardware", b"hardware", "headings", b"headings", "radios", b"radios", "software", b"software"]) -> None: ...

global___SystemInfo = SystemInfo

@typing_extensions.final
class StreamTarget(google.protobuf.message.Message):
    """Target address and general stream information"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _StreamLevel:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _StreamLevelEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[StreamTarget._StreamLevel.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        HEARTBEAT: StreamTarget._StreamLevel.ValueType  # 0
        TELEMETRY: StreamTarget._StreamLevel.ValueType  # 1
        DETECTION: StreamTarget._StreamLevel.ValueType  # 2
        SPECTRUM: StreamTarget._StreamLevel.ValueType  # 3

    class StreamLevel(_StreamLevel, metaclass=_StreamLevelEnumTypeWrapper): ...
    HEARTBEAT: StreamTarget.StreamLevel.ValueType  # 0
    TELEMETRY: StreamTarget.StreamLevel.ValueType  # 1
    DETECTION: StreamTarget.StreamLevel.ValueType  # 2
    SPECTRUM: StreamTarget.StreamLevel.ValueType  # 3

    ID_FIELD_NUMBER: builtins.int
    LEVEL_FIELD_NUMBER: builtins.int
    ADDRESS_FIELD_NUMBER: builtins.int
    PORT_FIELD_NUMBER: builtins.int
    HEARTBEAT_TIMEOUT_FIELD_NUMBER: builtins.int
    TELEMETRY_TIMEOUT_FIELD_NUMBER: builtins.int
    id: builtins.int
    """Crucial stream parameters"""
    level: global___StreamTarget.StreamLevel.ValueType
    address: builtins.str
    """Target address"""
    port: builtins.int
    heartbeat_timeout: builtins.int
    """Secondary stream parameters"""
    telemetry_timeout: builtins.int
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        level: global___StreamTarget.StreamLevel.ValueType = ...,
        address: builtins.str = ...,
        port: builtins.int = ...,
        heartbeat_timeout: builtins.int = ...,
        telemetry_timeout: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["address", b"address", "heartbeat_timeout", b"heartbeat_timeout", "id", b"id", "level", b"level", "port", b"port", "telemetry_timeout", b"telemetry_timeout"]) -> None: ...

global___StreamTarget = StreamTarget

@typing_extensions.final
class CommandError(google.protobuf.message.Message):
    """Error during execution of command"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _ErrorType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ErrorTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[CommandError._ErrorType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: CommandError._ErrorType.ValueType  # 0
        """Possible error types"""

    class ErrorType(_ErrorType, metaclass=_ErrorTypeEnumTypeWrapper): ...
    UNKNOWN: CommandError.ErrorType.ValueType  # 0
    """Possible error types"""

    TIME_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    @property
    def time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Basic error information"""
    type: global___CommandError.ErrorType.ValueType
    description: builtins.str
    """Detailed error message"""
    def __init__(
        self,
        *,
        time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        type: global___CommandError.ErrorType.ValueType = ...,
        description: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["time", b"time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["description", b"description", "time", b"time", "type", b"type"]) -> None: ...

global___CommandError = CommandError

@typing_extensions.final
class Command(google.protobuf.message.Message):
    """Common message encapsulating all possible commands"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    INSTRUCTION_FIELD_NUMBER: builtins.int
    PING_DATA_FIELD_NUMBER: builtins.int
    CONFIG_FIELD_NUMBER: builtins.int
    POSITION_FIELD_NUMBER: builtins.int
    TARGET_FIELD_NUMBER: builtins.int
    id: builtins.int
    """Unique ID of command"""
    instruction: global___Instruction.ValueType
    """Type of instruction"""
    ping_data: builtins.str
    """Ping data"""
    @property
    def config(self) -> global___Config:
        """Config information"""
    position: builtins.int
    """Playback position"""
    @property
    def target(self) -> global___StreamTarget:
        """Stream target"""
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        instruction: global___Instruction.ValueType = ...,
        ping_data: builtins.str = ...,
        config: global___Config | None = ...,
        position: builtins.int = ...,
        target: global___StreamTarget | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["config", b"config", "parameter", b"parameter", "ping_data", b"ping_data", "position", b"position", "target", b"target"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["config", b"config", "id", b"id", "instruction", b"instruction", "parameter", b"parameter", "ping_data", b"ping_data", "position", b"position", "target", b"target"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["parameter", b"parameter"]) -> typing_extensions.Literal["ping_data", "config", "position", "target"] | None: ...

global___Command = Command

@typing_extensions.final
class Response(google.protobuf.message.Message):
    """Common message encapsulating all possible responses"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    INSTRUCTION_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    PING_DATA_FIELD_NUMBER: builtins.int
    CONFIG_FIELD_NUMBER: builtins.int
    TELEMETRY_FIELD_NUMBER: builtins.int
    INFO_FIELD_NUMBER: builtins.int
    POSITION_FIELD_NUMBER: builtins.int
    id: builtins.int
    """Unique ID of command"""
    instruction: global___Instruction.ValueType
    """Type of instruction"""
    @property
    def error(self) -> global___CommandError: ...
    success: builtins.bool
    """Basic response indicating success of instruction"""
    ping_data: builtins.str
    """Ping data"""
    @property
    def config(self) -> global___Config:
        """Config information"""
    @property
    def telemetry(self) -> pysagax.message.data_pb2.Telemetry:
        """Telemetry information"""
    @property
    def info(self) -> global___SystemInfo:
        """System information"""
    position: builtins.int
    """Playback position"""
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        instruction: global___Instruction.ValueType = ...,
        error: global___CommandError | None = ...,
        success: builtins.bool = ...,
        ping_data: builtins.str = ...,
        config: global___Config | None = ...,
        telemetry: pysagax.message.data_pb2.Telemetry | None = ...,
        info: global___SystemInfo | None = ...,
        position: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["config", b"config", "data", b"data", "error", b"error", "info", b"info", "ping_data", b"ping_data", "position", b"position", "success", b"success", "telemetry", b"telemetry"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["config", b"config", "data", b"data", "error", b"error", "id", b"id", "info", b"info", "instruction", b"instruction", "ping_data", b"ping_data", "position", b"position", "success", b"success", "telemetry", b"telemetry"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["data", b"data"]) -> typing_extensions.Literal["success", "ping_data", "config", "telemetry", "info", "position"] | None: ...

global___Response = Response
