syntax = "proto3";
package pysagax.message;
import "google/protobuf/timestamp.proto";
import "pysagax/message/data.proto";
import "pysagax/message/heading.proto";
import "pysagax/message/altiss_intra_uav.proto";

enum Instruction {
    // Types of instructions that can be sent

    // Send a string, receive it back
    //   parameter: ping_data [string]
    //   response:  ping_data [string]
    PING = 0;

    // Set and query config information
    //   parameter: config [Config]
    //   response:  config [Config]
    CONFIG = 1;

    // Query telemetry information
    //   response:  telemetry [Telemetry]
    TELEMETRY = 2;

    // Query system information
    //   response:  info [Info]
    INFO = 3;

    // Status of Async config
    CONFIG_STATUS = 4;

    
    PY_RESET = 8;

    // Start CoreService
    //   response:  success [bool]
    CS_START = 9;

    // Stop CoreService
    //   response:  success [bool]
    CS_STOP = 10;

    // Restart CoreService
    //   response:  success [bool]
    CS_RESTART = 11;

    // Ping CoreService
    //   parameter: ping_data [string]
    //   response:  ping_data [string]
    CS_PING = 12;


    // Start playback from source
    //   response:  success [bool]
    SOURCE_START = 13;

    // Stop playback from source
    //   response:  success [bool]
    SOURCE_STOP = 14;

    // Set playback position
    //   parameter: position [uint64]
    //   response:  position [uint64]
    POSITION = 15;


    // Start recording
    //   response:  success [bool]
    REC_START = 17;

    // Stop recording
    //   response:  success [bool]
    REC_STOP = 18;


    // Start Heading service
    //   response:  success [bool]
    HEADING_START = 21;

    // Stop Heading service
    //   response: success [bool]
    HEADING_STOP = 22;

    // Restart Heading service
    //   response: success [bool]
    HEADING_RESTART = 23;


    // Start streaming to target
    //   parameter: target [StreamTarget]
    //   response:  success [bool]
    STREAM_START = 25;

    // Stop streaming to target, or to all targets if not specified
    //   parameter: target [StreamTarget] - level parameter will be ignored
    //   response:  success [bool]
    STREAM_STOP = 26;


    SELF_TEST = 28;

    // Message only for CoreService, it is required to upload a scan plan
    // before using this command.
    //   response: success [bool]
    CS_SCAN_START = 30;

    // Start calibration of radios.
    //   parameter: CalibrationCommand
    //   response:  success [bool]
    CS_CALIBRATE_START = 31;

    CS_CALIBRATE_ABORT = 32;

    // Turn phase compensation on/off.
    //   response:  success [bool]
    CS_TURN_OFF_COMPENSATION = 34;
    CS_TURN_ON_COMPENSATION = 35;
    
    CS_READ_PHASEDIFFS_FROM_FILE = 36;

    CS_CALIBRATION_VALUES_QUERY = 37;

    CS_CALIBRATION_PHASE_CHECK = 38;

    // ScanEngine control commands
    AUTO_CALIBRATION_ENABLE = 41;
    AUTO_CALIBRATION_DISABLE = 42;
    AUTO_CALIBRATION_TRIGGER = 43;
    CS_RELOAD_CONFIG = 44;


    // Forward the message to the Aviation Processing Module in Altiss
    //   parameter: MessageToAPM
    //   response:  success [bool]
    FORWARD_TO_APM = 50;

}

message ROIMask {
    // A single Region of Interest

    // ID for associating with Detections
    int32 roi_id = 1;

    // ROI parameters
    float center_frequency = 5;
    float span = 6;
    float threshold = 7;
}


message FreqList {
    uint32 iq_rate = 2;              // TODO: depracated?
    uint32 scan_burst_count = 4;         // Bursts per center frequency before hopping to the next one in scanning mode
    repeated float center_freqs = 3;
}

message FreqRange {
    float start = 1;
    float stop = 2;
}

message CoreServiceConfig {
    // CoreService parameters
    float center_frequency = 5;
    uint32 iq_rate = 6;
    float playback_speed = 7;
    uint64 bin_count = 8;
    uint64 burst_stride = 9;
    repeated int32 channel_gain = 10;

    // Source parameters
    string source_path = 17;
    string source_type = 19;
    string source_subdev = 20;
    uint64 aoa_antenna_id = 22; // indexing start from: 1; write: set the antenna descriptor; read: read the actual antenna descriptor
    uint32 aoa_antenna_count = 23; // the number of antenna presets; just read

    // Type of source
    enum Type {
        LIVE = 0;
        RECORDED = 1;
    }
    Type type = 18;
    FreqList scan_plan = 21;
}

message PostProcessingConfig {

    // ROI mask, made up of individual regions
    repeated ROIMask roi = 5;

    // PostProcessing parameters
    float mean_window = 11;
}

message Config {
    // Increments with every change. Used to validate streamed data against config
    uint32 config_id = 1;
    CoreServiceConfig cs = 2;
    PostProcessingConfig pp = 3;
    ScanEngineConfig se = 4;
    // Heading source selection
    HeadingConfig heading = 25;

}

message PhaseValues{
    repeated float phaseDiffs = 1;
    uint64 frequency = 2;
    repeated bool isValid = 3;
    google.protobuf.Timestamp validationDate = 5;
}

message CalibrationStatus {
    double phaseDiffValidTreshold = 1;
    repeated PhaseValues phaseValues = 2;
    string identifier = 3;
}

message ScanEngineConfig {
    enum Mode {
        MANUAL = 0;
        SCANNING = 1;
        TRACKING = 2;
    }
    Mode mode = 1;
    oneof parameter {
        ScanningConfig scanning = 6; // TODO: kiirtani?
        TrackingConfig tracking = 7;
    }

}

message ScanningConfig {
    repeated FreqRange ranges = 4;
}

message TrackedSignal {

    float frequency = 2;
    float bandwidth = 3;
}

message TrackingConfig {
    repeated TrackedSignal signals = 4;
    reserved 2, 3;
}


message SystemInfo {
    // General system information

    // Information about general hardware components
    message Hardware {
        uint32 disk = 1; // total disk space (megabytes)
        uint32 ram = 2; // total RAM (megabytes)
        string hostname = 10;
    }
    Hardware hardware = 1;

    // Information about software stack
    message Software {
        string cs_version = 1;
        string pysagax_version = 2;
    }
    Software software = 2;

    // Information about available Heading sources
    reserved 3;

    // Information about available SDR sources
    message SDR {
        // A single SDR source
        string model = 1;
    }
    repeated SDR radios = 4;
    HeadingStatus heading = 5;
}

message StreamTarget {
    // Target address and general stream information

    enum StreamLevel{
        HEARTBEAT = 0;
        TELEMETRY = 1;
        DETECTION = 2;
        SPECTRUM = 3;
    }

    // Crucial stream parameters
    int32 id = 1;
    StreamLevel level = 2;

    // Target address
    string address = 5;
    int32 port = 6;

    // Secondary stream parameters
    int32 heartbeat_timeout = 9;
    int32 telemetry_timeout = 10;

}

message CommandError {
    // Error during execution of command

    enum ErrorType {
        // Possible error types
        UNKNOWN = 0;
        // CoreServiceErrors
        NO_FILE_LOADED = 100;
        FAILED_TO_LOAD_CONFIG = 101;
        SOURCE_ERROR = 102;
        ACQUISITION_STATE_SOURCE_NOT_CONFIGURED = 103;
        MALFORMED_PARAMETER = 104;
        SET_AOA_BIN_COUNT_NOT_IN_SUPPORTED_SET = 105;
        BAD_PARAMETER_COUNT = 106;
        NOT_IMPLEMENTED_YET = 199;
    }

    // Basic error information
    google.protobuf.Timestamp time = 1;
    ErrorType type = 2;

    // Detailed error message
    string description = 5;
}


message CalibrationCommand {
    FreqList calibration_freqs = 11;
    string identifier = 12;

}

message MessageToAPM{
    // Wraps a message that we want to forward to the Avionics Processing Module in the Altiss project

    oneof payload {
        ComIntEmitterEvents emitter_events = 1;
    }
    
}

message Command {
    // Common message encapsulating all possible commands

    // Unique ID of command
    int32 id = 1;

    // Type of instruction
    Instruction instruction = 2;
    enum CommandKind {
        UNDEFINED = 0;
        READ = 1;
        WRITE = 2;
    }
    CommandKind kind = 3;
    // Parameter
    oneof parameter {
        // Ping data
        string ping_data = 5;

        // Config information
        Config config = 6;

        // Playback position
        uint64 position = 7;

        // Stream target
        StreamTarget target = 8;

        // Recording length
        uint64 rec_length_secs = 9;

        CalibrationCommand calib_command = 12;

        MessageToAPM msg_to_apm = 13; 
    }
    reserved 11;
    bool test =15;
}

message ConfigStatus {
    bool success = 1;

    map<string, string> responses = 2;

    int32 error_code = 4;
    string error_description = 5;

    google.protobuf.Timestamp start_time = 6;
    google.protobuf.Timestamp finish_time = 7;
    repeated string queue = 8;
}

message Response {
    // Common message encapsulating all possible responses

    // Unique ID of command
    int32 id = 1;

    // Type of instruction
    Instruction instruction = 2;
    CommandError error = 3;

    // Response data
    oneof data {
        // Basic response indicating success of instruction
        bool success = 5;

        // Ping data
        string ping_data = 6;

        // Config information
        Config config = 7;

        // Telemetry information
        Telemetry telemetry = 8;

        // System information
        SystemInfo info = 9;

        // Playback position
        uint64 position = 10;

        // Config Status
        ConfigStatus config_status = 11;
        // For Value query
        CalibrationStatus calib_values = 12;
    }
}
