"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import pysagax.message.data_pb2
import pysagax.message.heading_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _Instruction:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _InstructionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Instruction.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    PING: _Instruction.ValueType  # 0
    """Send a string, receive it back
      parameter: ping_data [string]
      response:  ping_data [string]
    """
    CONFIG: _Instruction.ValueType  # 1
    """Set and query config information
      parameter: config [Config]
      response:  config [Config]
    """
    TELEMETRY: _Instruction.ValueType  # 2
    """Query telemetry information
      response:  telemetry [Telemetry]
    """
    INFO: _Instruction.ValueType  # 3
    """Query system information
      response:  info [Info]
    """
    CONFIG_STATUS: _Instruction.ValueType  # 4
    """Status of Async config"""
    PY_RESET: _Instruction.ValueType  # 8
    CS_START: _Instruction.ValueType  # 9
    """Start CoreService
      response:  success [bool]
    """
    CS_STOP: _Instruction.ValueType  # 10
    """Stop CoreService
      response:  success [bool]
    """
    CS_RESTART: _Instruction.ValueType  # 11
    """Restart CoreService
      response:  success [bool]
    """
    CS_PING: _Instruction.ValueType  # 12
    """Ping CoreService
      parameter: ping_data [string]
      response:  ping_data [string]
    """
    SOURCE_START: _Instruction.ValueType  # 13
    """Start playback from source
      response:  success [bool]
    """
    SOURCE_STOP: _Instruction.ValueType  # 14
    """Stop playback from source
      response:  success [bool]
    """
    POSITION: _Instruction.ValueType  # 15
    """Set playback position
      parameter: position [uint64]
      response:  position [uint64]
    """
    REC_START: _Instruction.ValueType  # 17
    """Start recording
      response:  success [bool]
    """
    REC_STOP: _Instruction.ValueType  # 18
    """Stop recording
      response:  success [bool]
    """
    HEADING_START: _Instruction.ValueType  # 21
    """Start Heading service
      response:  success [bool]
    """
    HEADING_STOP: _Instruction.ValueType  # 22
    """Stop Heading service
      response: success [bool]
    """
    HEADING_RESTART: _Instruction.ValueType  # 23
    """Restart Heading service
      response: success [bool]
    """
    STREAM_START: _Instruction.ValueType  # 25
    """Start streaming to target
      parameter: target [StreamTarget]
      response:  success [bool]
    """
    STREAM_STOP: _Instruction.ValueType  # 26
    """Stop streaming to target, or to all targets if not specified
      parameter: target [StreamTarget] - level parameter will be ignored
      response:  success [bool]
    """
    CS_SCAN_START: _Instruction.ValueType  # 30
    """Message only for CoreService, it is required to upload a scan plan
    before using this command.
      response: success [bool]
    """
    CS_CALIBRATE_START: _Instruction.ValueType  # 31
    CS_CALIBRATE_ABORT: _Instruction.ValueType  # 32
    CS_COMPENSATE_WITH_PHASEDIFFS_STOP: _Instruction.ValueType  # 34
    CS_READ_PHASEDIFFS_FROM_FILE: _Instruction.ValueType  # 36

class Instruction(_Instruction, metaclass=_InstructionEnumTypeWrapper):
    """Types of instructions that can be sent"""

PING: Instruction.ValueType  # 0
"""Send a string, receive it back
  parameter: ping_data [string]
  response:  ping_data [string]
"""
CONFIG: Instruction.ValueType  # 1
"""Set and query config information
  parameter: config [Config]
  response:  config [Config]
"""
TELEMETRY: Instruction.ValueType  # 2
"""Query telemetry information
  response:  telemetry [Telemetry]
"""
INFO: Instruction.ValueType  # 3
"""Query system information
  response:  info [Info]
"""
CONFIG_STATUS: Instruction.ValueType  # 4
"""Status of Async config"""
PY_RESET: Instruction.ValueType  # 8
CS_START: Instruction.ValueType  # 9
"""Start CoreService
  response:  success [bool]
"""
CS_STOP: Instruction.ValueType  # 10
"""Stop CoreService
  response:  success [bool]
"""
CS_RESTART: Instruction.ValueType  # 11
"""Restart CoreService
  response:  success [bool]
"""
CS_PING: Instruction.ValueType  # 12
"""Ping CoreService
  parameter: ping_data [string]
  response:  ping_data [string]
"""
SOURCE_START: Instruction.ValueType  # 13
"""Start playback from source
  response:  success [bool]
"""
SOURCE_STOP: Instruction.ValueType  # 14
"""Stop playback from source
  response:  success [bool]
"""
POSITION: Instruction.ValueType  # 15
"""Set playback position
  parameter: position [uint64]
  response:  position [uint64]
"""
REC_START: Instruction.ValueType  # 17
"""Start recording
  response:  success [bool]
"""
REC_STOP: Instruction.ValueType  # 18
"""Stop recording
  response:  success [bool]
"""
HEADING_START: Instruction.ValueType  # 21
"""Start Heading service
  response:  success [bool]
"""
HEADING_STOP: Instruction.ValueType  # 22
"""Stop Heading service
  response: success [bool]
"""
HEADING_RESTART: Instruction.ValueType  # 23
"""Restart Heading service
  response: success [bool]
"""
STREAM_START: Instruction.ValueType  # 25
"""Start streaming to target
  parameter: target [StreamTarget]
  response:  success [bool]
"""
STREAM_STOP: Instruction.ValueType  # 26
"""Stop streaming to target, or to all targets if not specified
  parameter: target [StreamTarget] - level parameter will be ignored
  response:  success [bool]
"""
CS_SCAN_START: Instruction.ValueType  # 30
"""Message only for CoreService, it is required to upload a scan plan
before using this command.
  response: success [bool]
"""
CS_CALIBRATE_START: Instruction.ValueType  # 31
CS_CALIBRATE_ABORT: Instruction.ValueType  # 32
CS_COMPENSATE_WITH_PHASEDIFFS_STOP: Instruction.ValueType  # 34
CS_READ_PHASEDIFFS_FROM_FILE: Instruction.ValueType  # 36
global___Instruction = Instruction

@typing_extensions.final
class ROIMask(google.protobuf.message.Message):
    """A single Region of Interest"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ROI_ID_FIELD_NUMBER: builtins.int
    CENTER_FREQUENCY_FIELD_NUMBER: builtins.int
    SPAN_FIELD_NUMBER: builtins.int
    THRESHOLD_FIELD_NUMBER: builtins.int
    roi_id: builtins.int
    """ID for associating with Detections"""
    center_frequency: builtins.float
    """ROI parameters"""
    span: builtins.float
    threshold: builtins.float
    def __init__(
        self,
        *,
        roi_id: builtins.int = ...,
        center_frequency: builtins.float = ...,
        span: builtins.float = ...,
        threshold: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["center_frequency", b"center_frequency", "roi_id", b"roi_id", "span", b"span", "threshold", b"threshold"]) -> None: ...

global___ROIMask = ROIMask

@typing_extensions.final
class FreqList(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IQ_RATE_FIELD_NUMBER: builtins.int
    CENTER_FREQS_FIELD_NUMBER: builtins.int
    iq_rate: builtins.int
    @property
    def center_freqs(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    def __init__(
        self,
        *,
        iq_rate: builtins.int = ...,
        center_freqs: collections.abc.Iterable[builtins.float] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["center_freqs", b"center_freqs", "iq_rate", b"iq_rate"]) -> None: ...

global___FreqList = FreqList

@typing_extensions.final
class FreqRange(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    START_FIELD_NUMBER: builtins.int
    STOP_FIELD_NUMBER: builtins.int
    start: builtins.float
    stop: builtins.float
    def __init__(
        self,
        *,
        start: builtins.float = ...,
        stop: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["start", b"start", "stop", b"stop"]) -> None: ...

global___FreqRange = FreqRange

@typing_extensions.final
class CoreServiceConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Type:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _TypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[CoreServiceConfig._Type.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        LIVE: CoreServiceConfig._Type.ValueType  # 0
        RECORDED: CoreServiceConfig._Type.ValueType  # 1

    class Type(_Type, metaclass=_TypeEnumTypeWrapper):
        """Type of source"""

    LIVE: CoreServiceConfig.Type.ValueType  # 0
    RECORDED: CoreServiceConfig.Type.ValueType  # 1

    CENTER_FREQUENCY_FIELD_NUMBER: builtins.int
    IQ_RATE_FIELD_NUMBER: builtins.int
    PLAYBACK_SPEED_FIELD_NUMBER: builtins.int
    BIN_COUNT_FIELD_NUMBER: builtins.int
    BURST_STRIDE_FIELD_NUMBER: builtins.int
    CHANNEL_GAIN_FIELD_NUMBER: builtins.int
    SOURCE_PATH_FIELD_NUMBER: builtins.int
    SOURCE_TYPE_FIELD_NUMBER: builtins.int
    SOURCE_SUBDEV_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    SCAN_PLAN_FIELD_NUMBER: builtins.int
    center_frequency: builtins.float
    """CoreService parameters"""
    iq_rate: builtins.int
    playback_speed: builtins.float
    bin_count: builtins.int
    burst_stride: builtins.int
    @property
    def channel_gain(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    source_path: builtins.str
    """Source parameters"""
    source_type: builtins.str
    source_subdev: builtins.str
    type: global___CoreServiceConfig.Type.ValueType
    @property
    def scan_plan(self) -> global___FreqList: ...
    def __init__(
        self,
        *,
        center_frequency: builtins.float = ...,
        iq_rate: builtins.int = ...,
        playback_speed: builtins.float = ...,
        bin_count: builtins.int = ...,
        burst_stride: builtins.int = ...,
        channel_gain: collections.abc.Iterable[builtins.int] | None = ...,
        source_path: builtins.str = ...,
        source_type: builtins.str = ...,
        source_subdev: builtins.str = ...,
        type: global___CoreServiceConfig.Type.ValueType = ...,
        scan_plan: global___FreqList | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["scan_plan", b"scan_plan"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["bin_count", b"bin_count", "burst_stride", b"burst_stride", "center_frequency", b"center_frequency", "channel_gain", b"channel_gain", "iq_rate", b"iq_rate", "playback_speed", b"playback_speed", "scan_plan", b"scan_plan", "source_path", b"source_path", "source_subdev", b"source_subdev", "source_type", b"source_type", "type", b"type"]) -> None: ...

global___CoreServiceConfig = CoreServiceConfig

@typing_extensions.final
class PostProcessingConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ROI_FIELD_NUMBER: builtins.int
    MEAN_WINDOW_FIELD_NUMBER: builtins.int
    @property
    def roi(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ROIMask]:
        """ROI mask, made up of individual regions"""
    mean_window: builtins.float
    """PostProcessing parameters"""
    def __init__(
        self,
        *,
        roi: collections.abc.Iterable[global___ROIMask] | None = ...,
        mean_window: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["mean_window", b"mean_window", "roi", b"roi"]) -> None: ...

global___PostProcessingConfig = PostProcessingConfig

@typing_extensions.final
class Config(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONFIG_ID_FIELD_NUMBER: builtins.int
    CS_FIELD_NUMBER: builtins.int
    PP_FIELD_NUMBER: builtins.int
    SE_FIELD_NUMBER: builtins.int
    HEADING_FIELD_NUMBER: builtins.int
    config_id: builtins.int
    """Increments with every change. Used to validate streamed data against config"""
    @property
    def cs(self) -> global___CoreServiceConfig: ...
    @property
    def pp(self) -> global___PostProcessingConfig: ...
    @property
    def se(self) -> global___ScanEngineConfig: ...
    @property
    def heading(self) -> pysagax.message.heading_pb2.HeadingConfig:
        """Heading source selection"""
    def __init__(
        self,
        *,
        config_id: builtins.int = ...,
        cs: global___CoreServiceConfig | None = ...,
        pp: global___PostProcessingConfig | None = ...,
        se: global___ScanEngineConfig | None = ...,
        heading: pysagax.message.heading_pb2.HeadingConfig | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["cs", b"cs", "heading", b"heading", "pp", b"pp", "se", b"se"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["config_id", b"config_id", "cs", b"cs", "heading", b"heading", "pp", b"pp", "se", b"se"]) -> None: ...

global___Config = Config

@typing_extensions.final
class ScanEngineConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Mode:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ModeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ScanEngineConfig._Mode.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        MANUAL: ScanEngineConfig._Mode.ValueType  # 0
        SCANNING: ScanEngineConfig._Mode.ValueType  # 1
        TRACKING: ScanEngineConfig._Mode.ValueType  # 2

    class Mode(_Mode, metaclass=_ModeEnumTypeWrapper): ...
    MANUAL: ScanEngineConfig.Mode.ValueType  # 0
    SCANNING: ScanEngineConfig.Mode.ValueType  # 1
    TRACKING: ScanEngineConfig.Mode.ValueType  # 2

    MODE_FIELD_NUMBER: builtins.int
    SCANNING_FIELD_NUMBER: builtins.int
    TRACKING_FIELD_NUMBER: builtins.int
    mode: global___ScanEngineConfig.Mode.ValueType
    @property
    def scanning(self) -> global___ScanningConfig: ...
    @property
    def tracking(self) -> global___TrackingConfig: ...
    def __init__(
        self,
        *,
        mode: global___ScanEngineConfig.Mode.ValueType = ...,
        scanning: global___ScanningConfig | None = ...,
        tracking: global___TrackingConfig | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["parameter", b"parameter", "scanning", b"scanning", "tracking", b"tracking"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["mode", b"mode", "parameter", b"parameter", "scanning", b"scanning", "tracking", b"tracking"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["parameter", b"parameter"]) -> typing_extensions.Literal["scanning", "tracking"] | None: ...

global___ScanEngineConfig = ScanEngineConfig

@typing_extensions.final
class ScanningConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RANGES_FIELD_NUMBER: builtins.int
    @property
    def ranges(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FreqRange]: ...
    def __init__(
        self,
        *,
        ranges: collections.abc.Iterable[global___FreqRange] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["ranges", b"ranges"]) -> None: ...

global___ScanningConfig = ScanningConfig

@typing_extensions.final
class TrackedSignal(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FREQUENCY_FIELD_NUMBER: builtins.int
    BANDWIDTH_FIELD_NUMBER: builtins.int
    frequency: builtins.float
    bandwidth: builtins.float
    def __init__(
        self,
        *,
        frequency: builtins.float = ...,
        bandwidth: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["bandwidth", b"bandwidth", "frequency", b"frequency"]) -> None: ...

global___TrackedSignal = TrackedSignal

@typing_extensions.final
class TrackingConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SIGNALS_FIELD_NUMBER: builtins.int
    @property
    def signals(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TrackedSignal]: ...
    def __init__(
        self,
        *,
        signals: collections.abc.Iterable[global___TrackedSignal] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["signals", b"signals"]) -> None: ...

global___TrackingConfig = TrackingConfig

@typing_extensions.final
class SystemInfo(google.protobuf.message.Message):
    """General system information"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class Hardware(google.protobuf.message.Message):
        """Information about general hardware components"""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        DISK_FIELD_NUMBER: builtins.int
        HOSTNAME_FIELD_NUMBER: builtins.int
        disk: builtins.int
        hostname: builtins.str
        def __init__(
            self,
            *,
            disk: builtins.int = ...,
            hostname: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["disk", b"disk", "hostname", b"hostname"]) -> None: ...

    @typing_extensions.final
    class Software(google.protobuf.message.Message):
        """Information about software stack"""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        CS_VERSION_FIELD_NUMBER: builtins.int
        PYSAGAX_VERSION_FIELD_NUMBER: builtins.int
        cs_version: builtins.str
        pysagax_version: builtins.str
        def __init__(
            self,
            *,
            cs_version: builtins.str = ...,
            pysagax_version: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["cs_version", b"cs_version", "pysagax_version", b"pysagax_version"]) -> None: ...

    @typing_extensions.final
    class SDR(google.protobuf.message.Message):
        """Information about available SDR sources"""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        MODEL_FIELD_NUMBER: builtins.int
        model: builtins.str
        """A single SDR source"""
        def __init__(
            self,
            *,
            model: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["model", b"model"]) -> None: ...

    HARDWARE_FIELD_NUMBER: builtins.int
    SOFTWARE_FIELD_NUMBER: builtins.int
    RADIOS_FIELD_NUMBER: builtins.int
    HEADING_FIELD_NUMBER: builtins.int
    @property
    def hardware(self) -> global___SystemInfo.Hardware: ...
    @property
    def software(self) -> global___SystemInfo.Software: ...
    @property
    def radios(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SystemInfo.SDR]: ...
    @property
    def heading(self) -> pysagax.message.heading_pb2.HeadingStatus: ...
    def __init__(
        self,
        *,
        hardware: global___SystemInfo.Hardware | None = ...,
        software: global___SystemInfo.Software | None = ...,
        radios: collections.abc.Iterable[global___SystemInfo.SDR] | None = ...,
        heading: pysagax.message.heading_pb2.HeadingStatus | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["hardware", b"hardware", "heading", b"heading", "software", b"software"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["hardware", b"hardware", "heading", b"heading", "radios", b"radios", "software", b"software"]) -> None: ...

global___SystemInfo = SystemInfo

@typing_extensions.final
class StreamTarget(google.protobuf.message.Message):
    """Target address and general stream information"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _StreamLevel:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _StreamLevelEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[StreamTarget._StreamLevel.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        HEARTBEAT: StreamTarget._StreamLevel.ValueType  # 0
        TELEMETRY: StreamTarget._StreamLevel.ValueType  # 1
        DETECTION: StreamTarget._StreamLevel.ValueType  # 2
        SPECTRUM: StreamTarget._StreamLevel.ValueType  # 3

    class StreamLevel(_StreamLevel, metaclass=_StreamLevelEnumTypeWrapper): ...
    HEARTBEAT: StreamTarget.StreamLevel.ValueType  # 0
    TELEMETRY: StreamTarget.StreamLevel.ValueType  # 1
    DETECTION: StreamTarget.StreamLevel.ValueType  # 2
    SPECTRUM: StreamTarget.StreamLevel.ValueType  # 3

    ID_FIELD_NUMBER: builtins.int
    LEVEL_FIELD_NUMBER: builtins.int
    ADDRESS_FIELD_NUMBER: builtins.int
    PORT_FIELD_NUMBER: builtins.int
    HEARTBEAT_TIMEOUT_FIELD_NUMBER: builtins.int
    TELEMETRY_TIMEOUT_FIELD_NUMBER: builtins.int
    id: builtins.int
    """Crucial stream parameters"""
    level: global___StreamTarget.StreamLevel.ValueType
    address: builtins.str
    """Target address"""
    port: builtins.int
    heartbeat_timeout: builtins.int
    """Secondary stream parameters"""
    telemetry_timeout: builtins.int
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        level: global___StreamTarget.StreamLevel.ValueType = ...,
        address: builtins.str = ...,
        port: builtins.int = ...,
        heartbeat_timeout: builtins.int = ...,
        telemetry_timeout: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["address", b"address", "heartbeat_timeout", b"heartbeat_timeout", "id", b"id", "level", b"level", "port", b"port", "telemetry_timeout", b"telemetry_timeout"]) -> None: ...

global___StreamTarget = StreamTarget

@typing_extensions.final
class CommandError(google.protobuf.message.Message):
    """Error during execution of command"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _ErrorType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ErrorTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[CommandError._ErrorType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: CommandError._ErrorType.ValueType  # 0
        """Possible error types"""
        NO_FILE_LOADED: CommandError._ErrorType.ValueType  # 100
        """CoreServiceErrors"""
        FAILED_TO_LOAD_CONFIG: CommandError._ErrorType.ValueType  # 101
        SOURCE_ERROR: CommandError._ErrorType.ValueType  # 102
        ACQUISITION_STATE_SOURCE_NOT_CONFIGURED: CommandError._ErrorType.ValueType  # 103
        MALFORMED_PARAMETER: CommandError._ErrorType.ValueType  # 104
        SET_AOA_BIN_COUNT_NOT_IN_SUPPORTED_SET: CommandError._ErrorType.ValueType  # 105
        BAD_PARAMETER_COUNT: CommandError._ErrorType.ValueType  # 106
        NOT_IMPLEMENTED_YET: CommandError._ErrorType.ValueType  # 199

    class ErrorType(_ErrorType, metaclass=_ErrorTypeEnumTypeWrapper): ...
    UNKNOWN: CommandError.ErrorType.ValueType  # 0
    """Possible error types"""
    NO_FILE_LOADED: CommandError.ErrorType.ValueType  # 100
    """CoreServiceErrors"""
    FAILED_TO_LOAD_CONFIG: CommandError.ErrorType.ValueType  # 101
    SOURCE_ERROR: CommandError.ErrorType.ValueType  # 102
    ACQUISITION_STATE_SOURCE_NOT_CONFIGURED: CommandError.ErrorType.ValueType  # 103
    MALFORMED_PARAMETER: CommandError.ErrorType.ValueType  # 104
    SET_AOA_BIN_COUNT_NOT_IN_SUPPORTED_SET: CommandError.ErrorType.ValueType  # 105
    BAD_PARAMETER_COUNT: CommandError.ErrorType.ValueType  # 106
    NOT_IMPLEMENTED_YET: CommandError.ErrorType.ValueType  # 199

    TIME_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    @property
    def time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Basic error information"""
    type: global___CommandError.ErrorType.ValueType
    description: builtins.str
    """Detailed error message"""
    def __init__(
        self,
        *,
        time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        type: global___CommandError.ErrorType.ValueType = ...,
        description: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["time", b"time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["description", b"description", "time", b"time", "type", b"type"]) -> None: ...

global___CommandError = CommandError

@typing_extensions.final
class CalibrationCommand(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CALIBRATION_FREQS_FIELD_NUMBER: builtins.int
    IDENTIFIER_FIELD_NUMBER: builtins.int
    @property
    def calibration_freqs(self) -> global___FreqList: ...
    identifier: builtins.str
    def __init__(
        self,
        *,
        calibration_freqs: global___FreqList | None = ...,
        identifier: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["calibration_freqs", b"calibration_freqs"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["calibration_freqs", b"calibration_freqs", "identifier", b"identifier"]) -> None: ...

global___CalibrationCommand = CalibrationCommand

@typing_extensions.final
class Command(google.protobuf.message.Message):
    """Common message encapsulating all possible commands"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _CommandKind:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _CommandKindEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Command._CommandKind.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNDEFINED: Command._CommandKind.ValueType  # 0
        READ: Command._CommandKind.ValueType  # 1
        WRITE: Command._CommandKind.ValueType  # 2

    class CommandKind(_CommandKind, metaclass=_CommandKindEnumTypeWrapper): ...
    UNDEFINED: Command.CommandKind.ValueType  # 0
    READ: Command.CommandKind.ValueType  # 1
    WRITE: Command.CommandKind.ValueType  # 2

    ID_FIELD_NUMBER: builtins.int
    INSTRUCTION_FIELD_NUMBER: builtins.int
    KIND_FIELD_NUMBER: builtins.int
    PING_DATA_FIELD_NUMBER: builtins.int
    CONFIG_FIELD_NUMBER: builtins.int
    POSITION_FIELD_NUMBER: builtins.int
    TARGET_FIELD_NUMBER: builtins.int
    REC_LENGTH_SECS_FIELD_NUMBER: builtins.int
    CALIB_COMMAND_FIELD_NUMBER: builtins.int
    id: builtins.int
    """Unique ID of command"""
    instruction: global___Instruction.ValueType
    """Type of instruction"""
    kind: global___Command.CommandKind.ValueType
    ping_data: builtins.str
    """Ping data"""
    @property
    def config(self) -> global___Config:
        """Config information"""
    position: builtins.int
    """Playback position"""
    @property
    def target(self) -> global___StreamTarget:
        """Stream target"""
    rec_length_secs: builtins.int
    """Recording length"""
    @property
    def calib_command(self) -> global___CalibrationCommand: ...
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        instruction: global___Instruction.ValueType = ...,
        kind: global___Command.CommandKind.ValueType = ...,
        ping_data: builtins.str = ...,
        config: global___Config | None = ...,
        position: builtins.int = ...,
        target: global___StreamTarget | None = ...,
        rec_length_secs: builtins.int = ...,
        calib_command: global___CalibrationCommand | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["calib_command", b"calib_command", "config", b"config", "parameter", b"parameter", "ping_data", b"ping_data", "position", b"position", "rec_length_secs", b"rec_length_secs", "target", b"target"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["calib_command", b"calib_command", "config", b"config", "id", b"id", "instruction", b"instruction", "kind", b"kind", "parameter", b"parameter", "ping_data", b"ping_data", "position", b"position", "rec_length_secs", b"rec_length_secs", "target", b"target"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["parameter", b"parameter"]) -> typing_extensions.Literal["ping_data", "config", "position", "target", "rec_length_secs", "calib_command"] | None: ...

global___Command = Command

@typing_extensions.final
class ConfigStatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class ResponsesEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    SUCCESS_FIELD_NUMBER: builtins.int
    RESPONSES_FIELD_NUMBER: builtins.int
    ERROR_CODE_FIELD_NUMBER: builtins.int
    ERROR_DESCRIPTION_FIELD_NUMBER: builtins.int
    START_TIME_FIELD_NUMBER: builtins.int
    FINISH_TIME_FIELD_NUMBER: builtins.int
    QUEUE_FIELD_NUMBER: builtins.int
    success: builtins.bool
    @property
    def responses(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    error_code: builtins.int
    error_description: builtins.str
    @property
    def start_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def finish_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def queue(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        responses: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        error_code: builtins.int = ...,
        error_description: builtins.str = ...,
        start_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        finish_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        queue: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["finish_time", b"finish_time", "start_time", b"start_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["error_code", b"error_code", "error_description", b"error_description", "finish_time", b"finish_time", "queue", b"queue", "responses", b"responses", "start_time", b"start_time", "success", b"success"]) -> None: ...

global___ConfigStatus = ConfigStatus

@typing_extensions.final
class Response(google.protobuf.message.Message):
    """Common message encapsulating all possible responses"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    INSTRUCTION_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    PING_DATA_FIELD_NUMBER: builtins.int
    CONFIG_FIELD_NUMBER: builtins.int
    TELEMETRY_FIELD_NUMBER: builtins.int
    INFO_FIELD_NUMBER: builtins.int
    POSITION_FIELD_NUMBER: builtins.int
    CONFIG_STATUS_FIELD_NUMBER: builtins.int
    id: builtins.int
    """Unique ID of command"""
    instruction: global___Instruction.ValueType
    """Type of instruction"""
    @property
    def error(self) -> global___CommandError: ...
    success: builtins.bool
    """Basic response indicating success of instruction"""
    ping_data: builtins.str
    """Ping data"""
    @property
    def config(self) -> global___Config:
        """Config information"""
    @property
    def telemetry(self) -> pysagax.message.data_pb2.Telemetry:
        """Telemetry information"""
    @property
    def info(self) -> global___SystemInfo:
        """System information"""
    position: builtins.int
    """Playback position"""
    @property
    def config_status(self) -> global___ConfigStatus:
        """Config Status"""
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        instruction: global___Instruction.ValueType = ...,
        error: global___CommandError | None = ...,
        success: builtins.bool = ...,
        ping_data: builtins.str = ...,
        config: global___Config | None = ...,
        telemetry: pysagax.message.data_pb2.Telemetry | None = ...,
        info: global___SystemInfo | None = ...,
        position: builtins.int = ...,
        config_status: global___ConfigStatus | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["config", b"config", "config_status", b"config_status", "data", b"data", "error", b"error", "info", b"info", "ping_data", b"ping_data", "position", b"position", "success", b"success", "telemetry", b"telemetry"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["config", b"config", "config_status", b"config_status", "data", b"data", "error", b"error", "id", b"id", "info", b"info", "instruction", b"instruction", "ping_data", b"ping_data", "position", b"position", "success", b"success", "telemetry", b"telemetry"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["data", b"data"]) -> typing_extensions.Literal["success", "ping_data", "config", "telemetry", "info", "position", "config_status"] | None: ...

global___Response = Response
