"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import pysagax.message.heading_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class Telemetry(google.protobuf.message.Message):
    """Non-critical information changing regularly"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class Hardware(google.protobuf.message.Message):
        """Hardware info"""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        CPU_USAGE_FIELD_NUMBER: builtins.int
        DISK_USAGE_FIELD_NUMBER: builtins.int
        TEMPERATURE_FIELD_NUMBER: builtins.int
        HOSTNAME_FIELD_NUMBER: builtins.int
        cpu_usage: builtins.float
        disk_usage: builtins.int
        temperature: builtins.float
        hostname: builtins.str
        def __init__(
            self,
            *,
            cpu_usage: builtins.float = ...,
            disk_usage: builtins.int = ...,
            temperature: builtins.float = ...,
            hostname: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["cpu_usage", b"cpu_usage", "disk_usage", b"disk_usage", "hostname", b"hostname", "temperature", b"temperature"]) -> None: ...

    @typing_extensions.final
    class Source(google.protobuf.message.Message):
        """Source info"""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        class _Status:
            ValueType = typing.NewType("ValueType", builtins.int)
            V: typing_extensions.TypeAlias = ValueType

        class _StatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Telemetry.Source._Status.ValueType], builtins.type):
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
            DISABLED: Telemetry.Source._Status.ValueType  # 0
            ENABLED: Telemetry.Source._Status.ValueType  # 1
            RUNNING: Telemetry.Source._Status.ValueType  # 2

        class Status(_Status, metaclass=_StatusEnumTypeWrapper):
            """Source status"""

        DISABLED: Telemetry.Source.Status.ValueType  # 0
        ENABLED: Telemetry.Source.Status.ValueType  # 1
        RUNNING: Telemetry.Source.Status.ValueType  # 2

        STATUS_FIELD_NUMBER: builtins.int
        POSITION_FIELD_NUMBER: builtins.int
        LENGTH_FIELD_NUMBER: builtins.int
        status: global___Telemetry.Source.Status.ValueType
        position: builtins.int
        """Current position in selected source"""
        length: builtins.int
        """Length of selected source"""
        def __init__(
            self,
            *,
            status: global___Telemetry.Source.Status.ValueType = ...,
            position: builtins.int = ...,
            length: builtins.int = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["length", b"length", "position", b"position", "status", b"status"]) -> None: ...

    @typing_extensions.final
    class Recording(google.protobuf.message.Message):
        """Recording info"""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        class _Status:
            ValueType = typing.NewType("ValueType", builtins.int)
            V: typing_extensions.TypeAlias = ValueType

        class _StatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Telemetry.Recording._Status.ValueType], builtins.type):
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
            DISABLED: Telemetry.Recording._Status.ValueType  # 0
            ENABLED: Telemetry.Recording._Status.ValueType  # 1
            RUNNING: Telemetry.Recording._Status.ValueType  # 2

        class Status(_Status, metaclass=_StatusEnumTypeWrapper):
            """Recording status"""

        DISABLED: Telemetry.Recording.Status.ValueType  # 0
        ENABLED: Telemetry.Recording.Status.ValueType  # 1
        RUNNING: Telemetry.Recording.Status.ValueType  # 2

        STATUS_FIELD_NUMBER: builtins.int
        FILENAME_FIELD_NUMBER: builtins.int
        LENGTH_FIELD_NUMBER: builtins.int
        status: global___Telemetry.Recording.Status.ValueType
        filename: builtins.str
        """Path of recording being written"""
        length: builtins.int
        """Current length of recording"""
        def __init__(
            self,
            *,
            status: global___Telemetry.Recording.Status.ValueType = ...,
            filename: builtins.str = ...,
            length: builtins.int = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["filename", b"filename", "length", b"length", "status", b"status"]) -> None: ...

    TIME_FIELD_NUMBER: builtins.int
    STREAM_ID_FIELD_NUMBER: builtins.int
    HARDWARE_FIELD_NUMBER: builtins.int
    SOURCE_FIELD_NUMBER: builtins.int
    RECORDING_FIELD_NUMBER: builtins.int
    HEADING_FIELD_NUMBER: builtins.int
    @property
    def time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    stream_id: builtins.int
    @property
    def hardware(self) -> global___Telemetry.Hardware: ...
    @property
    def source(self) -> global___Telemetry.Source: ...
    @property
    def recording(self) -> global___Telemetry.Recording: ...
    @property
    def heading(self) -> pysagax.message.heading_pb2.HeadingStatus: ...
    def __init__(
        self,
        *,
        time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        stream_id: builtins.int = ...,
        hardware: global___Telemetry.Hardware | None = ...,
        source: global___Telemetry.Source | None = ...,
        recording: global___Telemetry.Recording | None = ...,
        heading: pysagax.message.heading_pb2.HeadingStatus | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["hardware", b"hardware", "heading", b"heading", "recording", b"recording", "source", b"source", "time", b"time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["hardware", b"hardware", "heading", b"heading", "recording", b"recording", "source", b"source", "stream_id", b"stream_id", "time", b"time"]) -> None: ...

global___Telemetry = Telemetry

@typing_extensions.final
class Detection(google.protobuf.message.Message):
    """A single detection instance"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EVENT_ID_FIELD_NUMBER: builtins.int
    ROI_ID_FIELD_NUMBER: builtins.int
    FREQUENCY_FIELD_NUMBER: builtins.int
    BANDWIDTH_FIELD_NUMBER: builtins.int
    STRENGTH_FIELD_NUMBER: builtins.int
    AZIMUTH_FIELD_NUMBER: builtins.int
    ELEVATION_FIELD_NUMBER: builtins.int
    SNR_FIELD_NUMBER: builtins.int
    DEVIATION_FIELD_NUMBER: builtins.int
    event_id: builtins.int
    """ID of Event to which it belongs"""
    roi_id: builtins.int
    """ID of source region"""
    frequency: builtins.float
    """General detection information"""
    bandwidth: builtins.float
    strength: builtins.float
    azimuth: builtins.float
    elevation: builtins.float
    snr: builtins.float
    deviation: builtins.float
    def __init__(
        self,
        *,
        event_id: builtins.int = ...,
        roi_id: builtins.int = ...,
        frequency: builtins.float = ...,
        bandwidth: builtins.float = ...,
        strength: builtins.float = ...,
        azimuth: builtins.float = ...,
        elevation: builtins.float = ...,
        snr: builtins.float = ...,
        deviation: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["azimuth", b"azimuth", "bandwidth", b"bandwidth", "deviation", b"deviation", "elevation", b"elevation", "event_id", b"event_id", "frequency", b"frequency", "roi_id", b"roi_id", "snr", b"snr", "strength", b"strength"]) -> None: ...

global___Detection = Detection

@typing_extensions.final
class Spectrum(google.protobuf.message.Message):
    """Spectrum data"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _SpectrumType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _SpectrumTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Spectrum._SpectrumType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        MAGNITUDE: Spectrum._SpectrumType.ValueType  # 0
        AZIMUTH: Spectrum._SpectrumType.ValueType  # 1
        ELEVATION: Spectrum._SpectrumType.ValueType  # 2

    class SpectrumType(_SpectrumType, metaclass=_SpectrumTypeEnumTypeWrapper):
        """Type of spectrum contained"""

    MAGNITUDE: Spectrum.SpectrumType.ValueType  # 0
    AZIMUTH: Spectrum.SpectrumType.ValueType  # 1
    ELEVATION: Spectrum.SpectrumType.ValueType  # 2

    class _DataType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _DataTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Spectrum._DataType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        INT16: Spectrum._DataType.ValueType  # 0
        INT8: Spectrum._DataType.ValueType  # 1
        FLOAT32: Spectrum._DataType.ValueType  # 5

    class DataType(_DataType, metaclass=_DataTypeEnumTypeWrapper):
        """Data type of data in byte array"""

    INT16: Spectrum.DataType.ValueType  # 0
    INT8: Spectrum.DataType.ValueType  # 1
    FLOAT32: Spectrum.DataType.ValueType  # 5

    CHANNEL_ID_FIELD_NUMBER: builtins.int
    SPECTRUM_TYPE_FIELD_NUMBER: builtins.int
    DATA_TYPE_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    CENTER_FREQUENCY_FIELD_NUMBER: builtins.int
    BANDWIDTH_FIELD_NUMBER: builtins.int
    channel_id: builtins.int
    spectrum_type: global___Spectrum.SpectrumType.ValueType
    data_type: global___Spectrum.DataType.ValueType
    data: builtins.bytes
    center_frequency: builtins.float
    bandwidth: builtins.float
    def __init__(
        self,
        *,
        channel_id: builtins.int = ...,
        spectrum_type: global___Spectrum.SpectrumType.ValueType = ...,
        data_type: global___Spectrum.DataType.ValueType = ...,
        data: builtins.bytes = ...,
        center_frequency: builtins.float = ...,
        bandwidth: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["bandwidth", b"bandwidth", "center_frequency", b"center_frequency", "channel_id", b"channel_id", "data", b"data", "data_type", b"data_type", "spectrum_type", b"spectrum_type"]) -> None: ...

global___Spectrum = Spectrum

@typing_extensions.final
class Measurement(google.protobuf.message.Message):
    """Constanstly steamed data"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TIME_FIELD_NUMBER: builtins.int
    STREAM_ID_FIELD_NUMBER: builtins.int
    CONFIG_ID_FIELD_NUMBER: builtins.int
    PACKET_ID_FIELD_NUMBER: builtins.int
    POSITION_FIELD_NUMBER: builtins.int
    HEADING_FIELD_NUMBER: builtins.int
    QUATERNION_FIELD_NUMBER: builtins.int
    OVERFLOW_FIELD_NUMBER: builtins.int
    PEAKS_FIELD_NUMBER: builtins.int
    HEADING_DATA_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    DETECTION_FIELD_NUMBER: builtins.int
    @property
    def time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    stream_id: builtins.int
    config_id: builtins.int
    """ID of configuration at time of measurement"""
    packet_id: builtins.int
    """Metadata"""
    position: builtins.int
    heading: builtins.float
    @property
    def quaternion(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    overflow: builtins.bool
    @property
    def peaks(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def heading_data(self) -> pysagax.message.heading_pb2.HeadingData: ...
    @property
    def data(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Spectrum]:
        """Spectrum data"""
    @property
    def detection(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Detection]:
        """Detections made on above spectrum"""
    def __init__(
        self,
        *,
        time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        stream_id: builtins.int = ...,
        config_id: builtins.int = ...,
        packet_id: builtins.int = ...,
        position: builtins.int = ...,
        heading: builtins.float = ...,
        quaternion: collections.abc.Iterable[builtins.float] | None = ...,
        overflow: builtins.bool = ...,
        peaks: collections.abc.Iterable[builtins.int] | None = ...,
        heading_data: pysagax.message.heading_pb2.HeadingData | None = ...,
        data: collections.abc.Iterable[global___Spectrum] | None = ...,
        detection: collections.abc.Iterable[global___Detection] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["heading_data", b"heading_data", "time", b"time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["config_id", b"config_id", "data", b"data", "detection", b"detection", "heading", b"heading", "heading_data", b"heading_data", "overflow", b"overflow", "packet_id", b"packet_id", "peaks", b"peaks", "position", b"position", "quaternion", b"quaternion", "stream_id", b"stream_id", "time", b"time"]) -> None: ...

global___Measurement = Measurement

@typing_extensions.final
class Event(google.protobuf.message.Message):
    """High-level ComInt event, aggregate of one or more Detections"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TIME_FIELD_NUMBER: builtins.int
    STREAM_ID_FIELD_NUMBER: builtins.int
    EVENT_ID_FIELD_NUMBER: builtins.int
    FREQUENCY_FIELD_NUMBER: builtins.int
    STRENGTH_FIELD_NUMBER: builtins.int
    LOB_FIELD_NUMBER: builtins.int
    CERTAINTY_FIELD_NUMBER: builtins.int
    DURATION_FIELD_NUMBER: builtins.int
    DETECTION_FIELD_NUMBER: builtins.int
    @property
    def time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    stream_id: builtins.int
    event_id: builtins.int
    """ID of event"""
    frequency: builtins.float
    """General information"""
    strength: builtins.float
    lob: builtins.float
    certainty: builtins.float
    duration: builtins.float
    @property
    def detection(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        stream_id: builtins.int = ...,
        event_id: builtins.int = ...,
        frequency: builtins.float = ...,
        strength: builtins.float = ...,
        lob: builtins.float = ...,
        certainty: builtins.float = ...,
        duration: builtins.float = ...,
        detection: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["detection", b"detection", "time", b"time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["certainty", b"certainty", "detection", b"detection", "duration", b"duration", "event_id", b"event_id", "frequency", b"frequency", "lob", b"lob", "stream_id", b"stream_id", "strength", b"strength", "time", b"time"]) -> None: ...

global___Event = Event

@typing_extensions.final
class OperationalError(google.protobuf.message.Message):
    """Error during operation (not during command execution)"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _ErrorType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ErrorTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[OperationalError._ErrorType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: OperationalError._ErrorType.ValueType  # 0
        """Possible error types"""

    class ErrorType(_ErrorType, metaclass=_ErrorTypeEnumTypeWrapper): ...
    UNKNOWN: OperationalError.ErrorType.ValueType  # 0
    """Possible error types"""

    TIME_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    @property
    def time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """General error information"""
    type: global___OperationalError.ErrorType.ValueType
    description: builtins.str
    """Detailed error message"""
    def __init__(
        self,
        *,
        time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        type: global___OperationalError.ErrorType.ValueType = ...,
        description: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["time", b"time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["description", b"description", "time", b"time", "type", b"type"]) -> None: ...

global___OperationalError = OperationalError
