"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _UTMFlightState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _UTMFlightStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_UTMFlightState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    STATE_UNKNOWN: _UTMFlightState.ValueType  # 0
    STATE_GROUND: _UTMFlightState.ValueType  # 1
    STATE_AIRBORNE: _UTMFlightState.ValueType  # 2
    STATE_EMERGENCY: _UTMFlightState.ValueType  # 3
    STATE_NOCTRL: _UTMFlightState.ValueType  # 4

class UTMFlightState(_UTMFlightState, metaclass=_UTMFlightStateEnumTypeWrapper): ...

STATE_UNKNOWN: UTMFlightState.ValueType  # 0
STATE_GROUND: UTMFlightState.ValueType  # 1
STATE_AIRBORNE: UTMFlightState.ValueType  # 2
STATE_EMERGENCY: UTMFlightState.ValueType  # 3
STATE_NOCTRL: UTMFlightState.ValueType  # 4
global___UTMFlightState = UTMFlightState

class _FlightDataUpdate:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _FlightDataUpdateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_FlightDataUpdate.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UPDATE_POSITION: _FlightDataUpdate.ValueType  # 0
    UPDATE_ATTITUDE: _FlightDataUpdate.ValueType  # 1
    UPDATE_MISSION: _FlightDataUpdate.ValueType  # 2

class FlightDataUpdate(_FlightDataUpdate, metaclass=_FlightDataUpdateEnumTypeWrapper): ...

UPDATE_POSITION: FlightDataUpdate.ValueType  # 0
UPDATE_ATTITUDE: FlightDataUpdate.ValueType  # 1
UPDATE_MISSION: FlightDataUpdate.ValueType  # 2
global___FlightDataUpdate = FlightDataUpdate

@typing.final
class Position(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LATITUDE_FIELD_NUMBER: builtins.int
    LONGITUDE_FIELD_NUMBER: builtins.int
    ELLIPSOID_HEIGHT_FIELD_NUMBER: builtins.int
    TIMESTAMP_UNIX_FIELD_NUMBER: builtins.int
    latitude: builtins.float
    """latitude in degree"""
    longitude: builtins.float
    """longitude in degree"""
    ellipsoid_height: builtins.float
    """altitude (WGS84) in meter"""
    timestamp_unix: builtins.int
    """time of applicability of position (microseconds since UNIX epoch)."""
    def __init__(
        self,
        *,
        latitude: builtins.float = ...,
        longitude: builtins.float = ...,
        ellipsoid_height: builtins.float = ...,
        timestamp_unix: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ellipsoid_height", b"ellipsoid_height", "latitude", b"latitude", "longitude", b"longitude", "timestamp_unix", b"timestamp_unix"]) -> None: ...

global___Position = Position

@typing.final
class Attitude(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    YAW_FIELD_NUMBER: builtins.int
    PITCH_FIELD_NUMBER: builtins.int
    ROLL_FIELD_NUMBER: builtins.int
    TIMESTAMP_FROM_BOOT_FIELD_NUMBER: builtins.int
    yaw: builtins.float
    """yaw in degree"""
    pitch: builtins.float
    """pitch in degree"""
    roll: builtins.float
    """roll in degree"""
    timestamp_from_boot: builtins.int
    """time since system boot in ms"""
    def __init__(
        self,
        *,
        yaw: builtins.float = ...,
        pitch: builtins.float = ...,
        roll: builtins.float = ...,
        timestamp_from_boot: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["pitch", b"pitch", "roll", b"roll", "timestamp_from_boot", b"timestamp_from_boot", "yaw", b"yaw"]) -> None: ...

global___Attitude = Attitude

@typing.final
class Mission(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AIR_SPEED_FIELD_NUMBER: builtins.int
    GROUND_SPEED_FIELD_NUMBER: builtins.int
    ALTITUDE_MLS_FIELD_NUMBER: builtins.int
    BATTERY_LEVEL_FIELD_NUMBER: builtins.int
    BATTERY_VOLTAGE_FIELD_NUMBER: builtins.int
    PAYLOAD_BAY_STATUS_FIELD_NUMBER: builtins.int
    FLIGHT_MODE_FIELD_NUMBER: builtins.int
    FLIGHT_STATUS_FIELD_NUMBER: builtins.int
    air_speed: builtins.float
    ground_speed: builtins.float
    """ground speed in meter/s"""
    altitude_mls: builtins.int
    """MLS altitude in meter/s"""
    battery_level: builtins.int
    """remaining battery energy in %"""
    battery_voltage: builtins.int
    """missing - battery voltage in volt"""
    payload_bay_status: builtins.bool
    """payload bay open (1) or not (0)"""
    flight_mode: builtins.int
    """missing - current flight mode"""
    flight_status: global___UTMFlightState.ValueType
    """current flight status"""
    def __init__(
        self,
        *,
        air_speed: builtins.float = ...,
        ground_speed: builtins.float = ...,
        altitude_mls: builtins.int = ...,
        battery_level: builtins.int = ...,
        battery_voltage: builtins.int = ...,
        payload_bay_status: builtins.bool = ...,
        flight_mode: builtins.int = ...,
        flight_status: global___UTMFlightState.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["air_speed", b"air_speed", "altitude_mls", b"altitude_mls", "battery_level", b"battery_level", "battery_voltage", b"battery_voltage", "flight_mode", b"flight_mode", "flight_status", b"flight_status", "ground_speed", b"ground_speed", "payload_bay_status", b"payload_bay_status"]) -> None: ...

global___Mission = Mission

@typing.final
class UAVFlightInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TIMESTAMP_FIELD_NUMBER: builtins.int
    POSITION_FIELD_NUMBER: builtins.int
    ATTITUDE_FIELD_NUMBER: builtins.int
    MISSION_FIELD_NUMBER: builtins.int
    DATA_UPDATE_FIELD_NUMBER: builtins.int
    data_update: global___FlightDataUpdate.ValueType
    """indicate updated field"""
    @property
    def timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """message timestamp"""

    @property
    def position(self) -> global___Position:
        """position message"""

    @property
    def attitude(self) -> global___Attitude:
        """attitude message"""

    @property
    def mission(self) -> global___Mission:
        """mission message"""

    def __init__(
        self,
        *,
        timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        position: global___Position | None = ...,
        attitude: global___Attitude | None = ...,
        mission: global___Mission | None = ...,
        data_update: global___FlightDataUpdate.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["attitude", b"attitude", "mission", b"mission", "position", b"position", "timestamp", b"timestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["attitude", b"attitude", "data_update", b"data_update", "mission", b"mission", "position", b"position", "timestamp", b"timestamp"]) -> None: ...

global___UAVFlightInfo = UAVFlightInfo
