# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pysagax/message/flight_info.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!pysagax/message/flight_info.proto\x12\x0fpysagax.message\x1a\x1fgoogle/protobuf/timestamp.proto\"a\n\x08Position\x12\x10\n\x08latitude\x18\x01 \x01(\x02\x12\x11\n\tlongitude\x18\x02 \x01(\x02\x12\x18\n\x10\x65llipsoid_height\x18\x03 \x01(\x02\x12\x16\n\x0etimestamp_unix\x18\x04 \x01(\x04\"Q\n\x08\x41ttitude\x12\x0b\n\x03yaw\x18\x01 \x01(\x02\x12\r\n\x05pitch\x18\x02 \x01(\x02\x12\x0c\n\x04roll\x18\x03 \x01(\x02\x12\x1b\n\x13timestamp_from_boot\x18\x04 \x01(\x04\"\xe1\x01\n\x07Mission\x12\x11\n\tair_speed\x18\x01 \x01(\x02\x12\x14\n\x0cground_speed\x18\x02 \x01(\x02\x12\x14\n\x0c\x61ltitude_mls\x18\x03 \x01(\r\x12\x15\n\rbattery_level\x18\x04 \x01(\r\x12\x17\n\x0f\x62\x61ttery_voltage\x18\x05 \x01(\r\x12\x1a\n\x12payload_bay_status\x18\x06 \x01(\x08\x12\x13\n\x0b\x66light_mode\x18\x07 \x01(\r\x12\x36\n\rflight_status\x18\x08 \x01(\x0e\x32\x1f.pysagax.message.UTMFlightState\"\xfb\x01\n\rUAVFlightInfo\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x08position\x18\x02 \x01(\x0b\x32\x19.pysagax.message.Position\x12+\n\x08\x61ttitude\x18\x03 \x01(\x0b\x32\x19.pysagax.message.Attitude\x12)\n\x07mission\x18\x04 \x01(\x0b\x32\x18.pysagax.message.Mission\x12\x36\n\x0b\x64\x61ta_update\x18\x05 \x01(\x0e\x32!.pysagax.message.FlightDataUpdate*p\n\x0eUTMFlightState\x12\x11\n\rSTATE_UNKNOWN\x10\x00\x12\x10\n\x0cSTATE_GROUND\x10\x01\x12\x12\n\x0eSTATE_AIRBORNE\x10\x02\x12\x13\n\x0fSTATE_EMERGENCY\x10\x03\x12\x10\n\x0cSTATE_NOCTRL\x10\x04*P\n\x10\x46lightDataUpdate\x12\x13\n\x0fUPDATE_POSITION\x10\x00\x12\x13\n\x0fUPDATE_ATTITUDE\x10\x01\x12\x12\n\x0eUPDATE_MISSION\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pysagax.message.flight_info_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_UTMFLIGHTSTATE']._serialized_start=751
  _globals['_UTMFLIGHTSTATE']._serialized_end=863
  _globals['_FLIGHTDATAUPDATE']._serialized_start=865
  _globals['_FLIGHTDATAUPDATE']._serialized_end=945
  _globals['_POSITION']._serialized_start=87
  _globals['_POSITION']._serialized_end=184
  _globals['_ATTITUDE']._serialized_start=186
  _globals['_ATTITUDE']._serialized_end=267
  _globals['_MISSION']._serialized_start=270
  _globals['_MISSION']._serialized_end=495
  _globals['_UAVFLIGHTINFO']._serialized_start=498
  _globals['_UAVFLIGHTINFO']._serialized_end=749
# @@protoc_insertion_point(module_scope)
