# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pysagax/message/heading.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'pysagax/message/heading.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dpysagax/message/heading.proto\x12\x0fpysagax.message\x1a\x1fgoogle/protobuf/timestamp.proto\"=\n\x10HeadingParameter\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\"\xa1\x02\n\rHeadingStatus\x12\x1e\n\x16\x61vailable_source_types\x18\x01 \x03(\t\x12\x1c\n\x14selected_source_type\x18\x02 \x01(\t\x12\x35\n\nparameters\x18\x03 \x03(\x0b\x32!.pysagax.message.HeadingParameter\x12\x0e\n\x06status\x18\n \x01(\t\x12Q\n\x12\x63\x61libration_status\x18\x0b \x03(\x0b\x32\x35.pysagax.message.HeadingStatus.CalibrationStatusEntry\x1a\x38\n\x16\x43\x61librationStatusEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xa4\x01\n\rHeadingConfig\x12\x1c\n\x14selected_source_type\x18\x01 \x01(\t\x12\x42\n\nparameters\x18\x02 \x03(\x0b\x32..pysagax.message.HeadingConfig.ParametersEntry\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xd5\x01\n\x0bHeadingData\x12\x11\n\tpacket_id\x18\x01 \x01(\x04\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\nquaternion\x18\x03 \x03(\x02\x12,\n\x08gps_time\x18\n \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07gps_lat\x18\x0b \x01(\x02\x12\x0f\n\x07gps_lon\x18\x0c \x01(\x02\x12\x10\n\x08\x61ltitude\x18\r \x01(\x02\x12\x0e\n\x06offset\x18\x05 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pysagax.message.heading_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEADINGSTATUS_CALIBRATIONSTATUSENTRY']._loaded_options = None
  _globals['_HEADINGSTATUS_CALIBRATIONSTATUSENTRY']._serialized_options = b'8\001'
  _globals['_HEADINGCONFIG_PARAMETERSENTRY']._loaded_options = None
  _globals['_HEADINGCONFIG_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_HEADINGPARAMETER']._serialized_start=83
  _globals['_HEADINGPARAMETER']._serialized_end=144
  _globals['_HEADINGSTATUS']._serialized_start=147
  _globals['_HEADINGSTATUS']._serialized_end=436
  _globals['_HEADINGSTATUS_CALIBRATIONSTATUSENTRY']._serialized_start=380
  _globals['_HEADINGSTATUS_CALIBRATIONSTATUSENTRY']._serialized_end=436
  _globals['_HEADINGCONFIG']._serialized_start=439
  _globals['_HEADINGCONFIG']._serialized_end=603
  _globals['_HEADINGCONFIG_PARAMETERSENTRY']._serialized_start=554
  _globals['_HEADINGCONFIG_PARAMETERSENTRY']._serialized_end=603
  _globals['_HEADINGDATA']._serialized_start=606
  _globals['_HEADINGDATA']._serialized_end=819
# @@protoc_insertion_point(module_scope)
