"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class HeadingParameter(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    name: builtins.str
    type: builtins.str
    value: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        type: builtins.str = ...,
        value: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name", b"name", "type", b"type", "value", b"value"]) -> None: ...

global___HeadingParameter = HeadingParameter

@typing_extensions.final
class HeadingStatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class CalibrationStatusEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    AVAILABLE_SOURCE_TYPES_FIELD_NUMBER: builtins.int
    SELECTED_SOURCE_TYPE_FIELD_NUMBER: builtins.int
    PARAMETERS_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    CALIBRATION_STATUS_FIELD_NUMBER: builtins.int
    @property
    def available_source_types(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    selected_source_type: builtins.str
    @property
    def parameters(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___HeadingParameter]: ...
    status: builtins.str
    @property
    def calibration_status(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    def __init__(
        self,
        *,
        available_source_types: collections.abc.Iterable[builtins.str] | None = ...,
        selected_source_type: builtins.str = ...,
        parameters: collections.abc.Iterable[global___HeadingParameter] | None = ...,
        status: builtins.str = ...,
        calibration_status: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["available_source_types", b"available_source_types", "calibration_status", b"calibration_status", "parameters", b"parameters", "selected_source_type", b"selected_source_type", "status", b"status"]) -> None: ...

global___HeadingStatus = HeadingStatus

@typing_extensions.final
class HeadingConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class ParametersEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    SELECTED_SOURCE_TYPE_FIELD_NUMBER: builtins.int
    PARAMETERS_FIELD_NUMBER: builtins.int
    selected_source_type: builtins.str
    @property
    def parameters(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    def __init__(
        self,
        *,
        selected_source_type: builtins.str = ...,
        parameters: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["parameters", b"parameters", "selected_source_type", b"selected_source_type"]) -> None: ...

global___HeadingConfig = HeadingConfig

@typing_extensions.final
class HeadingData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PACKET_ID_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    QUATERNION_FIELD_NUMBER: builtins.int
    GPS_TIME_FIELD_NUMBER: builtins.int
    GPS_LAT_FIELD_NUMBER: builtins.int
    GPS_LON_FIELD_NUMBER: builtins.int
    ALTITUDE_FIELD_NUMBER: builtins.int
    OFFSET_FIELD_NUMBER: builtins.int
    packet_id: builtins.int
    @property
    def timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """System time of the acquisition, used to synchronize heading to signal"""
    @property
    def quaternion(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        """in scalar-first form: [w, x, y, z]"""
    @property
    def gps_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Timestamp from the GPS if present, can be used to adjust system clock"""
    gps_lat: builtins.float
    gps_lon: builtins.float
    altitude: builtins.float
    """altitude (WGS84) in meter"""
    offset: builtins.float
    def __init__(
        self,
        *,
        packet_id: builtins.int = ...,
        timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        quaternion: collections.abc.Iterable[builtins.float] | None = ...,
        gps_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        gps_lat: builtins.float = ...,
        gps_lon: builtins.float = ...,
        altitude: builtins.float = ...,
        offset: builtins.float = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["gps_time", b"gps_time", "timestamp", b"timestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["altitude", b"altitude", "gps_lat", b"gps_lat", "gps_lon", b"gps_lon", "gps_time", b"gps_time", "offset", b"offset", "packet_id", b"packet_id", "quaternion", b"quaternion", "timestamp", b"timestamp"]) -> None: ...

global___HeadingData = HeadingData
