syntax = "proto3";

package pysagax.message;
import "google/protobuf/timestamp.proto";

message HeadingParameter {
    string name = 1;
    string type = 2;
    string value = 3;
}

message HeadingStatus {
    repeated string available_source_types = 1;
    string selected_source_type = 2;
    repeated HeadingParameter parameters = 3;
    string status = 10;
    map<string, string> calibration_status = 11;
}

message HeadingConfig {
    string selected_source_type = 1;
    map<string, string> parameters = 2;
}

message HeadingData {
    uint64 packet_id = 1;
    google.protobuf.Timestamp timestamp = 2;  // System time of the acquisition, used to synchronize heading to signal
    repeated float quaternion = 3;
    google.protobuf.Timestamp gps_time = 10;  // Timestamp from the GPS if present, can be used to adjust system clock
    float gps_lat = 11;
    float gps_lon = 12;
    float offset = 5;
}

