[project]
name = "pysagax"
version = "0.1.31+feb27demo"
authors = [
  { name="Peter Rigo", email="peter.rigo@sagaxcommunications.com" },
  { name="Aron Szabo", email="aron.szabo@sagaxcommunications.com" },
  { name="Benedek Szakali", email="benedek.szakali@sagaxcommunications.com" },
]
description = "Python helper libraries for Sagax DF products"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "tk",
    "numpy",
    "AHRS",
    "scipy",
    "pyserial",
    "pyftdi",
    "matplotlib",
    "PyVISA",
    "Pillow",
    "pyquaternion",
    "pandas",
    "tomli",
    "rich",
    "coloredlogs",
    "protobuf",
    "pyzmq",
    "click",
]

[tool.versioneer]
VCS = "git"
style = "pep440"
versionfile_source = "pysagax/_version.py"
tag_prefix = "v"

[build-system]
requires = ["setuptools", "wheel", "versioneer", "protoletariat"]
build-backend = "setuptools.build_meta"

[project.scripts]
aaronia-tcp-server = "pysagax.aaronia_tcp_server:main"
clitestclient = "pysagax.clitestclient:main"
cstestclient = "pysagax.cstestclient:main"
dfclient = "pysagax.dfclient:main"
spotclient = "pysagax.spotclient:main"
sigmfdisp = "pysagax.sigmfdisp:main"
pysagax-uav = "pysagax.pysagax_uav:main"
zmqtestclient = "pysagax.zmqtestclient:main"
clizmqclient = "pysagax.clizmqclient:main"
clizmqcommander = "pysagax.clizmqcommander:main"
