[project]
name = "pysagax"
version = "0.4.1"
authors = [
  { name="Peter Rigo", email="peter.rigo@sagaxcommunications.com" },
  { name="Aron Szabo", email="aron.szabo@sagaxcommunications.com" },
  { name="Benedek Szakali", email="benedek.szakali@sagaxcommunications.com" },
]
description = "Python helper libraries for Sagax DF products"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "tk",
    "numpy",
    "AHRS",
    "scipy>=1.12.0",
    "pyserial",
    "pyftdi",
    "matplotlib",
    "PyVISA",
    "Pillow",
    "pyquaternion",
    "pandas",
    "tomli",
    "rich",
    "coloredlogs",
    "protobuf==3.20.3",
    "pyzmq",
    "click",
    "sigmf",
    "transitions",
    "sqlalchemy",
    "flask",
    "marshmallow",
    "flask-marshmallow",
    "flask-sqlalchemy",
    "flask-marshmallow-openapi",
    "marshmallow-sqlalchemy",
    "psycopg2",
]

[project.optional-dependencies]
test = [
    "black",
    "mypy",
    "pytest",
    "pytest-cov",
    "pytest-mock",
]

[tool.versioneer]
VCS = "git"
style = "pep440"
versionfile_source = "pysagax/_version.py"
tag_prefix = "v"

[build-system]
requires = ["setuptools", "wheel", "versioneer"]
build-backend = "setuptools.build_meta"

[project.scripts]
dfclient = "pysagax.dfclient:main"
spotclient = "pysagax.spotclient:main"
sigmfdisp = "pysagax.sigmfdisp:main"
sigmfspectrum = "pysagax.sigmfspectrum:main"
pysagax-uav = "pysagax.pysagax_uav:main"
pysagax-heading = "pysagax.pysagax_heading:main"
zmqtestclient = "pysagax.zmqtestclient:main"
clizmqclient = "pysagax.clizmqclient:main"
clizmqcommander = "pysagax.clizmqcommander:main"
