[project]
name = "pysagax"
version = "0.5.23"
authors = [
  { name="Peter Rigo", email="peter.rigo@sagaxcommunications.com" },
  { name="Gergely Deak", email="gergely.deak@sagaxcommunications.com" },
  { name="Aron Szabo", email="aron.szabo@sagaxcommunications.com" },
  { name="Benedek Szakali", email="benedek.szakali@sagaxcommunications.com" },
]
description = "Python helper libraries for Sagax DF products"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "setuptools",
    "tk",
    "numpy",
    "AHRS",
    "scipy>=1.12.0",
    "pyserial",
    "pyftdi",
    "matplotlib",
    "PyVISA",
    "Pillow",
    "pyquaternion",
    "pandas",
    "tomli",
    "rich",
    "coloredlogs",
    "protobuf==3.20.3",
    "pyzmq",
    "click",
    "sigmf",
    "transitions",
    "pymavlink",
    "sqlalchemy",
    "flask",
    "flask-cors",
    "flask-socketio",
    "marshmallow",
    "flask-marshmallow",
    "flask-sqlalchemy",
    "flask-marshmallow-openapi",
    "marshmallow-sqlalchemy",
    "Werkzeug",
    "psycopg2",
    "geographiclib",
    "tqdm",
    "tkinter-tooltip",
    "psutil"
]

[project.optional-dependencies]
test = [
    "black",
    "mypy",
    "pytest",
    "pytest-cov",
    "pytest-mock",
]

[tool.versioneer]
VCS = "git"
style = "pep440"
versionfile_source = "pysagax/_version.py"
tag_prefix = "v"

[tool.setuptools]
packages = [
    "pysagax",
    "pysagax.common",
    "pysagax.communication",
    "pysagax.df",
    "pysagax.field",
    "pysagax.gnd",
    "pysagax.heading",
    "pysagax.message",
    "pysagax.source",
    "pysagax.spot",
    "pysagax.ui",
    "pysagax.util"
]

[build-system]
requires = ["setuptools", "wheel", "versioneer"]
build-backend = "setuptools.build_meta"

[project.scripts]
dfclient = "pysagax.dfclient:main"
spotclient = "pysagax.spotclient:main"
sigmfdisp = "pysagax.sigmfdisp:main"
sigmfspectrum = "pysagax.sigmfspectrum:main"
pysagax-uav = "pysagax.pysagax_uav:main"
pysagax-gnd = "pysagax.pysagax_gnd:main"
pysagax-gnd-api = "pysagax.pysagax_gnd_api:main"
pysagax-heading = "pysagax.pysagax_heading:main"
zmqtestclient = "pysagax.zmqtestclient:main"
clizmqclient = "pysagax.clizmqclient:main"
clizmqcommander = "pysagax.clizmqcommander:main"
detectrec-to-csv = "pysagax.analyzing_tools.detectrec_to_csv:main"
protorec-to-csv = "pysagax.analyzing_tools.protorec_to_csv:main"
plot-results = "pysagax.analyzing_tools.plot_results:main"
spectrogram-viewer = "pysagax.analyzing_tools.spectrogram_viewer:main"
flight-info-test-server = "pysagax.analyzing_tools.heading.flight_info_test_server:main"
