disk_path = '/'
level = 'INFO'
command_port = 5555
cs_host = "127.0.0.1"
cs_command_port = 12936
cs_stream_port = 12937
heading_host = "127.0.0.1"
heading_control_port = 5566
heading_stream_port = 5567

