[defaults]
host = '10.1.1.114'
encoder_port = 'COM6'
center_freq = '446M'
bandwith = '1M'
gain = '50'
bin_count = '1024'
burst_stride = '50000'
roi_center = '446.065M'
roi_span = '50k'
roi_threshold = '-40'
df_corrected_from_compass = false    #true: compass, false: encoder

[display]
fps = 25
max_bin_count = 1024
spectrum_graph_min_db = -120

[stats]
avg_window_size_bursts = 20

