syntax = "proto3";

enum Instruction {
    QUERY = 0;
    START = 1;
    STOP = 2;
    REC = 3;
}

message Command {
    Instruction type = 1;
    oneof parameter {
        // START command
        int32 start_id = 2;

        // STOP command
        int32 stop_id = 3;
    }
}

message Error {
    string description = 1;
}

message Response {
    Instruction type = 1;
    oneof data {
        // General error
        Error error = 2;

        // Query response
        string query_data = 3;
    }
}