import csv
import click
from google.protobuf.json_format import MessageToDict
from datetime import datetime
from tqdm import tqdm


def get_messages(source):
    from pysagax.message.proto_stream_to_file import FileStreamer

    file_streamer = FileStreamer(source, mode="playback")
    time_list, packet_list = file_streamer.read_all()
    return time_list, packet_list


def filter_message_types(timestamp_list, message_list, ignored_types):
    new_ts_list = []
    new_msg_list = []
    for ts, msg in tqdm(
        zip(timestamp_list, message_list), desc="Filtering message types"
    ):
        if msg.DESCRIPTOR.name not in ignored_types:
            new_ts_list.append(ts)
            new_msg_list.append(msg)
    return new_ts_list, new_msg_list


def flatten_dict(d, parent_key="", sep="."):
    items = []
    for k, v in d.items():
        new_key = f"{parent_key}{sep}{k}" if parent_key else k
        if isinstance(v, dict):
            items.extend(flatten_dict(v, new_key, sep=sep).items())
        elif isinstance(v, list):
            for i, item in enumerate(v):
                if isinstance(item, dict):
                    items.extend(flatten_dict(item, f"{new_key}{i}", sep=sep).items())
                else:
                    items.append((f"{new_key}{i}", item))
        else:
            items.append((new_key, v))
    return dict(items)


def flatten_message(message, parent_key="", sep=".", skips=[]):
    items = []
    for k, v in message.items():
        new_key = f"{parent_key}{sep}{k}" if parent_key else k
        if new_key in skips:
            continue
        if isinstance(v, dict):
            items.extend(flatten_message(v, new_key, sep, skips).items())
        elif isinstance(v, list):
            for i, item in enumerate(v):
                items.extend(
                    flatten_message({f"{k}{i}": item}, parent_key, sep, skips).items()
                )
        else:
            items.append((new_key, v))
    return dict(items)


def process_messages(messages, skip_fields):
    all_fields = set()
    processed_messages = []

    for message in tqdm(messages, desc="Processing messages"):
        processed_message = flatten_message(MessageToDict(message), skips=skip_fields)
        all_fields.update(processed_message.keys())
        processed_messages.append(
            {"packet_type": message.DESCRIPTOR.name} | processed_message
        )

    # return processed_messages, list(all_fields)
    return processed_messages, sorted(list(all_fields))


def write_csv(filename, rec_timestamps, messages, fields):

    with open(filename, "w", newline="") as csvfile:
        writer = csv.DictWriter(
            csvfile,
            fieldnames=["record_time", "record_time_str", "packet_type"] + fields,
        )
        writer.writeheader()
        for ts, message in tqdm(
            zip(rec_timestamps, messages), desc="Writing .csv", total=len(messages)
        ):
            writer.writerow(
                {"record_time": ts, "record_time_str": datetime.fromtimestamp(ts)}
                | message
            )


@click.command()
@click.argument("source", type=click.STRING)
@click.argument("output", type=click.Path(), required=False)
@click.option(
    "--skip-field",
    "-s",
    multiple=True,
    help="Fields to skip from .csv. Useful for large fields such as spectrum data.",
)
@click.option(
    "--skip-type",
    "-i",
    multiple=True,
    help="Protobuf message types to skip from saving",
)
def main(source, output, skip_field, skip_type):
    """Convert protobuf messages to CSV.
    (can be used on files generated by pysagax.message.proto_stream_to_file.FileStreamer, despite the message types)

    SOURCE is the source for the messages.
    OUTPUT is the output CSV file name (not required).
    """
    if not output:
        output = ".".join(source.split(".")[:-1] + ["csv"])
    print("Reading messages")
    rec_timestamps, messages = get_messages(source)

    # print("Filtering message types")
    rec_timestamps, messages = filter_message_types(rec_timestamps, messages, skip_type)

    # print("Processing messages")
    processed_messages, fields = process_messages(messages, skip_field)

    # print("Saving csv")
    write_csv(output, rec_timestamps, processed_messages, fields)

    print(f"CSV file '{output}' has been created successfully.")

    return len(messages)


if __name__ == "__main__":
    main()
