syntax = "proto3";
import "google/protobuf/timestamp.proto";

enum Instruction {
    HEARTBEAT = 0;
    START = 1;
    STOP = 2;
    REC = 3;
    POSITION = 4;
    CONFIG = 5;
    QUERY = 6;
}

message Command {
    Instruction type = 1;
    oneof parameter {
        // START command
        int32 start_id = 2;

        // STOP command
        int32 stop_id = 3;

        uint64 position = 4;
        Configuration config;
    }
}

message Response {
    Instruction type = 1;
    oneof data {
        // General error

        Error error = 2;

        // Query response
        string query_data = 3;
        StatusResponse status = 4;
        Configuration config;
    }
}

message Error {
    string description = 1;
}

enum CoreServiceState {
    NONE = 0;
    CONFIGURED = 1;
    RUNNING = 2;
    RECORDING = 3;
}

enum SourceKind {
    LIVE = 0;
    RECORDED = 1;
}

message StatusResponse {
    CoreServiceState state = 1;
    uint64 length = 2;  // total [samples] in source
    uint64 position = 3;  // position in [samples]
    uint32 sample_rate = 4;
    float playback_speed = 5;
    SourceKind source_kind = 6;
    SDRInfo sdr_info = 7;
    string source_module = 8;
    bool recording_active = 9;
}

message SDRInfo {
    string model = 1;
}

message Configuration {
    string source_module = 1;
    repeated string source_parameters = 2;
    uint32 iq_rate = 3;
    float playback_speed = 4;
    uint64 burst_stride = 5;
    uint64 bin_count = 6;
    float center_frequency = 7;
    map<int32, int32> channel_gain = 8;
    repeated ROIMask roi_masks = 9;
    HeadingConfiguration heading_configuration = 10;
}

message HeadingConfiguration {
    repeated string available_heading_types;
    string selected_heading_type;
    map<string, string> heading_parameter_types;
    map<string, string> heading_parameter_values;
}

message ROIMask {
    fixed32 roi_id = 3;
    float center_frequency = 4;
    float span = 5;
    float threshold = 6;
}
